### PR TITLE
Added the ability to specify a custom webpack.mix.js file as well as …

### PR DESCRIPTION
**Pull request by VinceG**
This addresses the following two issues:

#607 
#608

I can comment to describe why i've made the changes the way they are. it might seem like it doesn't make sense but it's been working.

This has been working and tested on a public repository you can test this branch with

https://github.com/VinceG/laravel-mix-issue-manifest

### CODE REVIEW

**Comment by VinceG** [comment]
Kept testing and it looks like #607 is still an issue. this PR only fixes #608 right now. i am still looking into #607.

However, if we Merge this PR this will, in a way, fix #607 as well. Since now we will be able to use multiple webpack.mix.js files and separate the .js().extract() code into multiple files.

**Comment by QWp6t** [comment]
Oh, I just noticed this after replying to one of your issues. lol oh well. :man_facepalming:

**Comment by VinceG** [comment]
@JeffreyWay This has been running very well without any issues on 3 of our sites.

https://avn.com (NSFW)
http://webmasteraccess.com
http://gayvnawards.com

Sample mix-manifest.json file once we run all 3 sites

```
{
  "/modules/wma/build/js/app.js": "/modules/wma/build/js/app.84b5ef90c2bde47d245f.js",
  "/modules/wma/build/css/app.css": "/modules/wma/build/css/app.0f6a87810121d2c212a1.css",
  "/modules/wma/build/js/vendor.js": "/modules/wma/build/js/vendor.d5914bd10a5a9762ae19.js",
  "/modules/wma/build/js/manifest.js": "/modules/wma/build/js/manifest.d41d8cd98f00b204e980.js",
  "/maverick/css/vendor.css": "/maverick/css/vendor.0246cefcac97ef75424f8e313088efef.css",
  "/modules/awards/css/awards/all.css": "/modules/awards/css/awards/all.dcc2267a6f818c0031e2a46251888b8d.css",
  "/modules/awards/css/awards/vendor.css": "/modules/awards/css/awards/vendor.6d2a05f28e6a3791d5d863176d7edd4e.css",
  "/modules/awards/css/voting/all.css": "/modules/awards/css/voting/all.46770d711c88d7ec2ae482c8440c6f62.css",
  "/modules/awards/css/voting/vendor.css": "/modules/awards/css/voting/vendor.ec3bb52a00e176a7181d454dffaea219.css",
  "/maverick/css/all.css": "/maverick/css/all.b63676689ad74d96003919a006b53def.css",
  "/modules/awards/js/awards/vendor.js": "/modules/awards/js/awards/vendor.a6e810bf54e1ccb9cb168525bbfe3b8c.js",
  "/modules/awards/js/awards/all.js": "/modules/awards/js/awards/all.8e07c493dfedb49bf7b296841338f5f5.js",
  "/modules/awards/js/voting/vendor.js": "/modules/awards/js/voting/vendor.094db5b8570c1f9abae550410eb4a155.js",
  "/modules/awards/js/voting/all.js": "/modules/awards/js/voting/all.8e07c493dfedb49bf7b296841338f5f5.js",
  "/maverick/js/vendor.js": "/maverick/js/vendor.07a7db1171a45fe500c3c9887f59b1a8.js",
  "/maverick/js/all.js": "/maverick/js/all.cb6ab9f4d5bd0616cc7c6303c175db66.js",
  "/modules/admin/avn/css/all.css": "/modules/admin/avn/css/all.e521e4e5c4549a991fdd7735c5e60a2e.css",
  "/modules/admin/avn/js/vendor.js": "/modules/admin/avn/js/vendor.0f40583131f654fcf4cacd9a18d8a5da.js",
  "/modules/admin/avn/js/modules.js": "/modules/admin/avn/js/modules.fdb064c55f669f2c1b70b27064d07547.js",
  "/modules/admin/avn/js/all.js": "/modules/admin/avn/js/all.ea93ba9e4aa3e0dacc180df545aa985b.js",
  "/mix.js": "/mix.2c859f2861cff8603409.js",
  "/modules/gayvnawards/build/vendor.js": "/modules/gayvnawards/build/vendor.a93d315bb9bc47da7aa9.js",
  "/modules/gayvnawards/build/app.js": "/modules/gayvnawards/build/app.3d86bde6fce2e60b0794.js",
  "/modules/gayvnawards/build/css/app.css": "/modules/gayvnawards/build/css/app.d8694cb6e3959093d851.css",
  "/modules/gayvnawards/build/manifest.js": "/modules/gayvnawards/build/manifest.d41d8cd98f00b204e980.js"
}
```

Let me know if this is something you'll consider and i'll resolve the conflicts.

**Comment by trixan** [comment]
npm run dev -- --env.mixfile=custom.mix
not working,
npm run development -- --env.mixfile=custom.mix
is working your PR in Laravel 5.4

**Comment by VinceG** [comment]
Right it's just a type it should be development 

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by Vercoutere** [comment]
This is exactly what I was looking to do right now. Glad I checked Github beforehand.
Thanks for the effort @VinceG!

**Comment by VinceG** [comment]
@Vercoutere thanks for trying. let us know what you think and if everything works well. i think laravel mix will benefit from this and it has no BC breaks with the way it's setup right now. @JeffreyWay

**Comment by trixan** [comment]
Thank you @VinceG! Good job! Perfect works for me.
Examples:
```
npm run development -- --env.mixfile=webpack.plugins.mix
npm run development -- --env.mixfile=webpack.images.mix
npm run development -- --env.mixfile=webpack.theme1.mix
npm run development -- --env.mixfile=webpack.theme2.mix
```
or
```
npm run production -- --env.mixfile=webpack.frontend.mix
npm run production -- --env.mixfile=webpack.backend.mix

```
...etc

**Comment by Broutard** [comment]
+1

**Comment by VinceG** [comment]
@trixan are you using mix.version() ? does it work properly with versioning too?

**Comment by trixan** [comment]
@VinceG I only use mix.version 0.10.0

**Comment by VinceG** [comment]
🎉 🎉 🎉 🎉 🎉 
Thank You! @JeffreyWay

**Comment by trixan** [comment]
Thank You! @JeffreyWay

**Pull request merged**
