### PR TITLE
Add ability to compile less and sass files

### PR DESCRIPTION
**Pull request by donnysim**
Adds ability to compile less and sass files in one go,

```
mix.less('resources/assets/less/style.less', 'public/assets/css/less.css')
   .less('resources/assets/less/style2.less', 'public/assets/css/less2.css')
   .sass('resources/assets/sass/style2.scss', 'public/assets/css')
   .sass('resources/assets/sass/style.scss', 'public/assets/css');
```

### CODE REVIEW

**Comment by renatomjunior22** [comment]
I need this in one go too! I write my styles in less, but I need bootstrap 12/24-col grid system! (Which is in sass/scss)

**Comment by patie** [comment]
possible solution https://github.com/JeffreyWay/laravel-mix/issues/184#issuecomment-275385555

**Comment by JeffreyWay** [comment]
Thanks for the PR! There were a few naming things here that didn't gel well, so I pushed a commit to add support just now. It'll be tagged later today.

**Comment by donnysim** [comment]
No problem, now I can compile both and it's all that matters :)

**Pull request closed without merging**
