### PR TITLE
make combined files working with version! issue #270

### PR DESCRIPTION
**Pull request by forehalo**
image
image

[#270](https://github.com/JeffreyWay/laravel-mix/issues/270)

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Thanks for this. One thing I noticed is that you're passing an array of files to `mix.version()`. But your PR doesn't support that, right?

**Comment by forehalo** [comment]
@JeffreyWay Uh, the array passed was not used. We should still use `mix.version()` to generate versioned files. It was to show they can be versioned successfully, nothing else.

**Comment by JeffreyWay** [comment]
Okay this is merged in now. Thanks!

**Comment by iraklisg** [comment]
@forehalo thank you so much for this helpful addition!  @JeffreyWay the current npm version of laravel-mix@6.0.3 does not support this feature yet. Are there any plans to be included in laravel-mix@6.0.4

**Comment by JeffreyWay** [comment]
Yes - it'll be tagged once I do some more testing.

**Comment by nejtr0n** [comment]
it still not combine compiled version css. For example
```
.sass('admin/core.scss', 'public/css/admin/core.css')
.combine([
'public/css/admin/extra.css',
'public/css/admin/core.css'
], 'public/css/admin/all.css'
).version()
```
I've got an error - file not founded.
(because public/css/admin/core.css has versioned name like core.asdase242.css)

**Comment by iraklisg** [comment]
@nejtr0n the same here, the PR has not yet been accepted so patience :stuck_out_tongue: However, until the issue is solved, I think that @JeffreyWay should consider changing the [docs](https://github.com/JeffreyWay/laravel-mix/commit/27902ec2f6720e39156e9ed1b111c15fbfc634db#diff-bb1bd93b5077affc1930c467e3197e96R55) where it is implied that versionning applies  to combined files too

**Comment by rjvim** [comment]
Is this fix available in "laravel-mix": "^0.8.1", Sorry It's not clear if this fix is already available as I am facing the same issue.

**Comment by JeffreyWay** [comment]
@iraklisg The PR has been accepted, so no changes to the docs are needed.

https://www.dropbox.com/s/jrz4ri46k5cr2sv/Screenshot%202017-02-19%2015.23.48.png?dl=0

**Comment by JeffreyWay** [comment]
@nejtr0n You're getting an error because `public/css/admin/core.css` doesn't exist. You requested versioning, so it create the hashed version of that file. Then, you're trying to combine that file, but, again, because it doesn't exist, it fails. 

Instead, use a regular expression.

```js
.sass('admin/core.scss', 'public/css/admin/core.css')
.combine([
    'public/css/admin/extra.css',
    'public/css/admin/core.*.css'
], 'public/css/admin/all.css')
.version()
```

**Comment by nejtr0n** [comment]
Thank you! Didn't know about ability of regexp in combine =)

**Pull request closed without merging**
