### PR TITLE
Add Angular Babel Support

### PR DESCRIPTION
**Pull request by Log1x**
Came across #678 while cleaning up a clients project and it looked simple enough...

Also fixed some minor spacing inconsistencies and added `@param` to TypeScript's docblock in `Api.js`

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Do you need to also update the default Babel presets to reflect this?

https://github.com/JeffreyWay/laravel-mix/blob/master/src/config.js#L250-L252

**Comment by Log1x** [comment]
:) Whoops. Missed that when doing a search through the files.

I was also looking at [this](https://www.npmjs.com/package/babel-plugin-angularjs-annotate) to handle Angular 1.x but am unsure how to go about naming conventions. `.angular()`, `.angular2()` ?

**Comment by JeffreyWay** [comment]
It's a bit of a slippery slope adding helpers for all these different JS frameworks. My instinct is to just stick with what we have for now. 

Thanks though!

**Comment by ovflowd** [comment]
I'm really curious why the author of this package just doesn't add support for angular. That's a really **important** feature. I just cannot do versioning on my angular controllers with laravel mix and that, honestly sucks.

I really hope the author of this package, shows some respect to what the community wants, and adds further support for this feature. Isn't just cool having support to laravel, is necessary.

` slope adding helpers for all these different JS frameworks`

you could say the same about css frameworks, or are you just lazy to add support to the mainstream frameworks like react, angular and vue?

Sorry I'm not intending to be disrespectful, but seriously. That sucks.

**Comment by FrenchMajesty** [comment]
Bringing this back up.

@JeffreyWay Angular is one of the world's most popular front-end framework.. It sits in the top 3 right behind React and Vue. Is that not good enough of a reason for support should be included?

**Pull request closed without merging**
