### PR TITLE
Distinguish between image SVG and font SVG

### PR DESCRIPTION
**Pull request by tpraxl**
Both, fonts and images may be .svg files.

Before this commit, laravel-mix would consider all *.svg files to be font files. When resolved (e.g. because it was referred to in a scss file), they would have been copied to the fonts directory.

Now, laravel-mix distinguishes between the two types by considering their names or paths:

* font recognition pattern: `font.*\.svg$` will resolve font.svg, font2.svg and font/awesome.svg
* image recognition pattern: `im[a]?g.*\.svg$` will resolve img/1.svg and img1.svg

Images will be resolved and copied into the `images` directory, fonts will be resolved and copied into the `fonts` directory.

### CODE REVIEW

**Comment by kohenkatz** [comment]
I have been overriding the generated Webpack config to do this myself for a while, and I'm very happy to see a PR for it, but I see one issue - what happens to SVG files that aren't in a directory (or otherwise named with) with `font` or `im[a]?g`?

**Comment by tpraxl** [comment]
> what happens to SVG files that aren't in a directory (or otherwise named with) with font or im[a]?g?

Thanks for the point. They wouldn't be picked up at all.  

Maybe I should update the PR for default handling of either fonts or images (I would vote for images).

To be honest: If it was for my opinion, I would remove the font-handling for svg files completely. But I followed some of the discussions and have perceived that Jeffrey Way wants to keep the support.

I would appreciate opinions on this: Should svg files that don't match any of these patterns be handled as images or as fonts?

**Comment by kohenkatz** [comment]
I agree with leaving support for using SVG fonts - even though all modern browsers support WOFF and most of them support other options too - just because there's no reason not to.

That said, personally, I think anything that is not *explicitly* a font should be handled as an image.

**Comment by tpraxl** [comment]
Thanks. I'll wait for some other options and will update the PR during the next days.

**Comment by tpraxl** [comment]
@JeffreyWay Which option would you prefer? 

a) Consider an SVG an image unless its name has the font-pattern?
b) Consider an SVG a font unless its name has the image pattern?

**Comment by tpraxl** [comment]
Just updated the PR to fix the following issue pointed out by @kohenkatz 

If an svg did not contain the words img, image or font in the path or filename, it would not have been picked up at all.

Per default, all svg files are now considered images, **except** when the word "font" appears in the path or filename.

So the following files would be considered fonts for example:

* font/awesome.svg
* fonts/awesome.svg
* assets/font.svg

All other svg files would be considered images.

I also extended the test to verify that the files are not accidently handled by both webpack rules.

The image rule is implemented using a negative lookahead.

**Comment by JeffreyWay** [comment]
Okay, I'm going to merge this. 

Thanks for taking care of it, @tpraxl! I'll make a new release this week.

**Comment by JeffreyWay** [comment]
@tpraxl So what do you think... is this enough of a breaking change that we should tag a major release? Not sure.

**Comment by tpraxl** [comment]
Yes I think it justifies a major release.

**Comment by tpraxl** [comment]
Projects that dealt with images ending up in the fonts folder might have used static references like ``. So it's a breaking change that should justify the major version. I would expect that lots of projects went this way instead of using `{{ mix(…) }}`, because I think that laravel-mix is used outside laravel a lot.

**Comment by JeffreyWay** [comment]
Yeah good point. Okay, 2.0 it is.

**Comment by aminraeisi** [comment]
@tpraxl I just updated today and saw this change in my changed files. I have some place holder images that are stored in `storage/app/public/photos/i/` and I use them when there is no image uploaded by the user (profile images/shops logo/user image/etc).
All the placeholders are called in my blade files except one that was in my vuejs file. Now I have only that image created in my `public/images/` folder.
So the src that I had before was:
``
But with this update I can do this:
``
Which is better but only helps with one of the placeholders. Is there a way to have those other images like this?

**Pull request merged**
