### PR TITLE
Remove notification timeout, fixes #2161

### LINKED ISSUE #2161: Notifications not showing in KDE 5.16 because of hardcoded timeout
-   Laravel Mix Version: 4.1.2 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.6.0
-   NPM Version (`npm -v`): 6.10.1
-   OS: Kubuntu 19.04 with KDE 5.16

### Description:

I can see the notification for 2 ms instead of 2 seconds.

See screencast:

mix

The problem is coming from Mix because if I use WebpackNotifierPlugin directly it works:

```
var WebpackNotifierPlugin = require('webpack-notifier');

mix.webpackConfig(webpack => {
    return {
        plugins: [
            new WebpackNotifierPlugin({alwaysNotify: true}),
        ]
    };
});
```

results in

image

After digging further, I understood that for KDE, setting a timeout to 2 is 2ms.

https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Notifications.js#L18

 If I set it to 2000 then I'm getting 2 seconds:
```
mix.webpackConfig(webpack => {
    return {
        plugins: [
            new WebpackNotifierPlugin({
                title: 'Laravel Mix 2',
                alwaysNotify: Config.notifications.onSuccess,
                hint:
                    process.platform === 'linux'
                        ? 'int:transient:1'
                        : undefined,
                timeout: 2000, // 2000 instead of 2
                contentImage: Mix.paths.root(
                    'node_modules/laravel-mix/icons/laravel.png'
                ),
            }),
        ]
    };
});
```

Interestingly if I set the title to Laravel Mix and not Laravel Mix 2, then the notification only shows for 2 ms. I guess this is because KDE suppresses duplicate notifications.

This PR is to blame: https://github.com/JeffreyWay/laravel-mix/pull/1890

Please revert it as it is not working universally, or make it configurable with no value by default.

KDE allows setting a timeout per program so it should not be done there IMO.

Thanks

### PR DESCRIPTION
**Pull request by AdrienPoupa**
Remove timeout notification, this breaks the notifications on KDE

https://github.com/JeffreyWay/laravel-mix/issues/2161

### CODE REVIEW

**Comment by vokamut** [comment]
@JeffreyWay please merge changes

**Comment by vokamut** [comment]
@ecreeth please merge changes

**Comment by JeffreyWay** [comment]
Not without a description why we're removing it.

**Comment by AdrienPoupa** [comment]
There is ample description here:

https://github.com/JeffreyWay/laravel-mix/pull/2165
https://github.com/JeffreyWay/laravel-mix/issues/2161

**Comment by JeffreyWay** [comment]
Thanks @AdrienPoupa. Sorry for the wait.

**Comment by AdrienPoupa** [comment]
No problem, thank you!

**Comment by rodrigopedra** [comment]
Hi @AdrienPoupa great fix, thanks.

Hi @JeffreyWay , can we get a tagged release including this fix? No hurry, right now I am hard coding the commit hash in my `package.json` but it would be nice to have a release with this fix.

**Comment by vokamut** [comment]
> Hi @AdrienPoupa great fix, thanks.
> 
> Hi @JeffreyWay , can we get a tagged release including this fix? No hurry, right now I am hard coding the commit hash in my `package.json` but it would be nice to have a release with this fix.

Issue exists: https://github.com/JeffreyWay/laravel-mix/issues/2311

**Pull request merged**
