### PR TITLE
Update vue-loader to 13.0.5.

### PR DESCRIPTION
**Pull request by yansern**
`js-beautify` broke and `vue-loader` switched to prettier. #1194 

See:
https://github.com/beautify-web/js-beautify/issues/1247
https://twitter.com/vuejs/status/909785891941617664

### CODE REVIEW

**Comment by ruchern** [comment]
Did you try checking if this will break anything else? Going from v12 to v13 might break something thus I did not really want to bump the version earlier.

**Comment by yansern** [comment]
I have that concern myself too. But I've tested building my vue files on laravel with v13 and it went well. Replace laravel-mix in your package.json to `"laravel-mix": "yansern/laravel-mix",` and see if yours compile fine?

**Comment by ThomHurks** [comment]
After updating to Laravel-Mix 1.4.4 I suddenly get this Vue error: ```vue.common.js:478 [Vue warn]: Failed to mount component: template or render function not defined.``` and none of my single-file components work anymore. I would assume it's caused by the vue-loader change. Reverting to 1.4.3 fixes my issue and Vue works fine. Any idea what's wrong?

**Comment by yansern** [comment]
@ThomHurks If you use `require('foo.vue')` you'll need to change it to `require('foo.vue').default`. See: https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

I just realized I use `import` instead of `require` when loading vue files that's why I wasn't getting any errors.

@JeffreyWay I think I need to submit another pull request, adding `esModule: false` on the vue-loader options on the the `webpack-rules.js` file for backwards compatibility. See: https://github.com/vuejs/vue-loader/blob/master/docs/en/options.md#esmodule

**Comment by ThomHurks** [comment]
Ah, I'm using ```import``` for Vue and Vue plugins, but I'm using ```require``` for my own components. I'll try switching to using ```import``` or ```require().default``` for those. Probably a good idea to put this in the release notes :)

**Comment by JeffreyWay** [comment]
Ah yeah this is a breaking change. Need to fix that. @yansern can you submit that second PR?

**Comment by yansern** [comment]
@JeffreyWay Done. Hope this works!

**Pull request merged**
