### PR TITLE
The people have spoken - SVG needs to be removed

### PR DESCRIPTION
**Pull request by stephan-v**
https://github.com/JeffreyWay/laravel-mix/issues/1231
https://github.com/JeffreyWay/laravel-mix/pull/672
https://github.com/JeffreyWay/laravel-mix/issues/350
https://github.com/JeffreyWay/laravel-mix/issues/550
https://github.com/JeffreyWay/laravel-mix/issues/214

I can go on and find more but I doubt that is necessary. 

Nothing will break due to this change and I do not see how at this point with more and more complaints coming in that this can be ignored any longer.

### CODE REVIEW

**Comment by ankurk91** [comment]
Will wepack still pick SVG files referenced in source code?
Some people might be using SVG as images not only as fonts.

**Comment by stephan-v** [comment]
Update your mix.webpackConfig. If you want case-specific packages to work and have their .svg fonts resolved you should create a rule for it. Not the other way around.

Bootstrap 4 dropped the SVG fonts for a good reason and there are plenty of ways to work around font-awesome.

The default should be not to treat .svg files as fonts. I should not have to create counter-rules simply because some packages(who are all moving away from svg fonts mind you) still use them.

I'm happy to hear about legitimate concerns but so far I see none.

**Comment by ruchern** [comment]
@stephan-v There will be potential problems with Font Awesome. Looking at the v5 milestone, it does not seem like they are going to drop the SVG fonts for some reason.

**Comment by stephan-v** [comment]
There is no problem if you extend your webpack config like I said before, if you want to deal with it expand upon the existing config.

If you really do not want to tackle this issue then atleast allow for the API to opt out of svg fonts.

**Comment by ruchern** [comment]
@stephan-v I am not saying that we should not go ahead with this but since the depreciation of SVG fonts, Font Awesome should follow.

However, in order for Jeffrey Way to start implementing this into the package, these packages like Font Awesome have to comply first otherwise there would be too much work to do the checks in the code itself.

**Comment by ankurk91** [comment]
I also wants to get rid of `svg` fonts but what if i am calling svg image file in my code somewhere.
```js
let logo = require('./img/company-logo.svg');
```
We should have a loader to handle these files.
Consider moving `svg` to img loader.

**Comment by stephan-v** [comment]
Ok I hear you if that is the case. 

I will see if I have time to work on a solution which should make it easier to opt out of the SVG rule.

**Comment by stephan-v** [comment]
> However, in order for @JeffreyWay to start implementing this into the package, these packages like Font Awesome have to comply first otherwise there would be too much work to do the checks in the code itself and to deconflict for the users is another story.

Again like I said it will be **your job** to override your webpack config and opt in to use SVG's as fonts. This should not be the default case. This would require no code re-work here, just in your local project. As it should be, since you want to do something that falls out of the default norm.

SVG fonts are being deprecated and I can supply the dozens of comments again who are in favor of dropping this but I would rather not.

Moving `svg` to the img loader is fine by me.

**Comment by jm-mwi** [comment]
Where is the info that SVG fonts are being removed? The only references I found (with an admittedly short search) were from 10+ years ago @ Mozilla.

I'm not taking a stance, just looking for the references to the fact that SVG fonts are gone.

**Comment by ankurk91** [comment]
@jm-mwi 
https://caniuse.com/#search=svg%20fonts

**Comment by tpraxl** [comment]
+1 for removing svg fonts or at least do something that matches most use cases:

```js
// images
test: /(\.(png|jpe?g|gif)$|im[a]?g.*\.svg$)/,
// fonts
test: /(\.(woff2?|ttf|eot|otf)$|font.*\.svg$)/,
```
I was very surprised that this behavior is still the default in mix. :/

**Comment by ruchern** [comment]
@tpraxl a PR will be good for this.

**Comment by tpraxl** [comment]
@ruchern I would love to make a PR, but I can't manage to let the tests pick up on URLs in my scss fixture. So I'm currently unable to write a test for this, but I'll try to figure it out.

**Comment by tpraxl** [comment]
https://github.com/JeffreyWay/laravel-mix/pull/1367

The mix manifest didn't reflect the resolved image / fonts, so I struggled for some time to write the test. 
Now, I really hope that this reflects most of the use cases and will make it into laravel-mix.

**Comment by JeffreyWay** [comment]
One of these two PRs will be merged for the next major release. Will try to have that released before the end of the year.

**Comment by domstubbs** [comment]
It would be so helpful to be able to provide an array of overrides for each of the default rules’ tests and excludes, at least then there would be a simple solution where people have differing use cases. I appreciate that it is supposed to be possible to do that kind of thing via webpackConfig() but I’ve spent ages trying to just move SVGs from the font loader to the image loader and it doesn’t seem to be possible without modifying webpack.config.js as well. Even then, if you want to largely retain the default config it’s pretty awkward.

FWIW, I was able to override one of the simpler default rules using webpackConfig() in the past and from looking around I think this might be a [limitation of webpack-merge](https://github.com/survivejs/webpack-merge/issues/89) with function type configs. I think that would explain why I could override the JS rule but not the font one.

**Comment by JeffreyWay** [comment]
Fixed in #1367.

**Pull request closed without merging**
