### PR TITLE
Update webpack-dev-server to 3.1.10

### PR DESCRIPTION
**Pull request by ChienDevIT**
https://www.npmjs.com/advisories/725

### CODE REVIEW

**Comment by ChienDevIT** [comment]
Excuse me for not being careful. I have repaired at your request

**Comment by pahan35** [comment]
Looks like the build is failed due to missed **babel-preset-react**.
@JeffreyWay how did you handle this test before?

**Comment by ankurk91** [comment]
https://github.com/JeffreyWay/laravel-mix/pull/1815

**Comment by JeffreyWay** [comment]
We can't bump to this version until Mix upgrades to webpack 4 or higher.

**Pull request closed without merging**
