### PR TITLE
Add support for variable expansion

### PR DESCRIPTION
**Pull request by eberkund**
See #884

### CODE REVIEW

**Comment by ruchern** [comment]
Why do you need to install additional packages?

Just commit the following in #884 into `.env.example`

**Comment by eberkund** [comment]
This isn't for the PHP side of things, which already supports variable expansion through _phpdotenv_. 

This is for the [enviroment variables ](https://laravel.com/docs/5.4/mix#environment-variables) feature of mix which is useful for injecting constants into your JavaScript.

**Comment by HSPDev** [comment]
I think this is fine. @eberkund is right, the PHP side of things doesn't matter, as the .env file is passed by JS, and I actually see this as a bug, as laravel-mix might misbehave/break, if you are already using expansion in your .env file in Laravel, and try to run Laravel mix.

**Comment by ankurk91** [comment]
ping @JeffreyWay 
Can we get this merged, this gonna be very useful.

**Pull request merged**
