### PR TITLE
Allow configuration of ProvidePlugin through “autoloading”

### PR DESCRIPTION
**Pull request by thecrypticace**
I've added `mix.autoload()` to configure webpack's ProvidePlugin. This should solve the problem in issue https://github.com/JeffreyWay/laravel-mix/issues/96 with libraries that use jQuery. h/t to @QWp6t in that thread for the example API which I've implemented here.

Example usage:
```js
mix.autoload({
  'jquery': ['$', 'window.jQuery', 'jQuery'],
});
```

I've got it on my todo list to add tests to verify this works. Just wanted to get a PR out there to start a conversation on the suggested API.

### CODE REVIEW

**Comment by JeffreyWay** [comment]
We can do this...but I really hate that folks would be expected to call this method..

**Comment by thecrypticace** [comment]
I do agree on that. I spent a little time trying to figure out a way to override ProvidePlugin but failed to find something helpful. Perhaps jQuery could be in the default set of autoloads and calling it with an empty `{}` could remove them? I'm still not sold on that but it's the best I can come up with at the moment.

**Comment by eblin** [comment]
@thecrypticace @JeffreyWay  I think a good solution would be, have sensible defaults that work for the 80% of use cases. In this case have jquery be loaded by default like you said and pass the empty obj to remove it if you want. 

It would be very similar to how `Mix.babelConfig()` method works.

**Comment by thecrypticace** [comment]
Updated.

**Comment by bvangraafeiland** [comment]
Would be nice to have this, the way it is now you have to add jquery to package.json even if you don't use it.

**Pull request merged**
