### PR TITLE
webpack 5 RC and dependency updates

### PR DESCRIPTION
**Pull request by thecrypticace**
What it says on the tin. I've upgraded to the latest webpack 5 beta as well as updated some loaders and a few other dependencies.

**Note:**
I upgraded `webpack-merge` to 5.0. It removed the smart merge strategy (which appears to only do smart merging on `preLoaders`, `loaders`, `postLoaders`, and `rules` keys) so I ported that code over w/ references to the source it was taken from.

Ideally we'd determine what merging strategy we actually want but that will require some thought and plenty of input from the community so I put in a warning saying that it will change w/ the next Major mix version (v7.0) as something that can be tackled later. The warning appears only once per invocation of Mix _if_ one calls `.webpackConfig(…)`.

### CODE REVIEW

**Comment by thecrypticace** [comment]
If I have time this weekend (🤞) I might tackle refactoring the path normalization as windows is currently failing CI due to path-related problems.

**Comment by victorsilent** [comment]
@JeffreyWay @thecrypticace any luck with webpack 5 upgrade?

**Comment by thecrypticace** [comment]
Yeah, I've been continually updating this PR to keep it updated with the betas. webpack 5 should be getting a release candidate in the next week or two and I'll ping Jeffrey then to take a look at this PR again.

Currently though everything appears to be passing. There are some warnings thrown for `.vue` files because of mini-css-extract-plugin (I think…) but I don't _think_ they're affecting anything but I need to look into it some more.

**Comment by victorsilent** [comment]
Huge thanks!
I'm asking just because right now I'm not able to extract libraries using .extract due the bug related with .css files being empty
and this have a performance impact on my app =/

**Comment by thecrypticace** [comment]
Alright @JeffreyWay webpack got it's rc.0 release yesterday and I've updated the PR. All the tests pass. Probably a good time to get another alpha / beta version out.

It's on my todo list to update `postcss-loader` to 4.0 but that causes some test failures so I've got to figure that one out.

**Comment by JeffreyWay** [comment]
Okay, merging this now. Thanks, Jordan.

**Pull request merged**
