### PR TITLE
Feature/babel7

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
Motivated by wanting to use _newer_ babel plugins, I have updated laravel-mix to babel7. All other dependencies are carefully updated to the latest version without breaking backwards-compatibility or requiring a rewrite of laravel-mix.

Main thing to do next is to upgrade webpack3 to 4, which only requires a rewrite of `MixDefinitionsPlugin.prototype.getDefinitions` and removing some pieces from the various configurations. I'm blissfully unaware of the consequences for people using laravel-mix, so I didn't attempt it in this PR.

However, this is a major semver release, even though I was aiming for a minor release, there is no way to upgrade to babel7 if not people also upgrade to babel7.

Locally I had one error when running the tests, before changing any code:
```
ERROR  Failed to compile with 1 errors

 error  in ./test/fixtures/fake-app/resources/assets/js/app.js

Module build failed: Error: Couldn't find preset "react" relative to directory "/Users/nappdev/projects/opensource/laravel-mix/test/fixtures/fake-app/resources/assets/js"
    at /Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/nappdev/projects/opensource/laravel-mix/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

 @ multi ./test/fixtures/fake-app/resources/assets/js/app.js ./test/fixtures/fake-app/resources/assets/sass/app.scss
```

Which after upgrading to babel7, turned into the following error:

```
ERROR  Failed to compile with 1 errors

 error  in ./test/fixtures/fake-app/resources/assets/js/app.js

Module build failed: Error: Cannot find module '@babel/preset-react' from '/Users/nappdev/projects/opensource/laravel-mix'
    at Function.module.exports [as sync] (/Users/nappdev/projects/opensource/laravel-mix/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at passPerPreset (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:58:96)
    at cachedFunction (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/caching.js:33:19)
    at presets.presets (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/nappdev/projects/opensource/laravel-mix/node_modules/@babel/core/lib/config/partial.js:85:55)

 @ multi ./test/fixtures/fake-app/resources/assets/js/app.js ./test/fixtures/fake-app/resources/assets/sass/app.scss
```

Quite the same but removed by adding `@babel/preset-react` to `devDependencies`. Not sure why `Preact` does not throw the same error as the two classes are virtually identical. I imagine it has something to do with [`Dependencies.install`](https://github.com/JeffreyWay/laravel-mix/blob/52582c120f2eaef0146d63a43c41235f40e3f030/src/Dependencies.js#L14).
```js
install(abortOnComplete = false) {
    this.dependencies
        .reject(dependency => {
            try {
                return require.resolve(
                    dependency.replace(/(?!^@)@.+$/, '') // <- seems to be removing scope from npm packages
                );
            } catch (e) {}
        })
```

Main difference is to install `@babel/plugin-[name]` instead of `babel-plugin-[name]` and fixing `.babelrc` since babel7 will throw error when it sees unknown property name. 

Migrate list for laravel-mix users:
- [ ] In `package.json`, change all occurrences of `"babel-plugin-[name]": "6.x"` to `"@babel/plugin-[name]": "7.x"`
- [ ] In `.babelrc` change all occurrences of plugins to version 7 , e.i.`"plugins": ["babel-plugin-transform-object-rest-spread"]` to `"plugins": ["@babel/plugin-proposal-object-rest-spread"]`

=====================
Ref: fixing #1760

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
We have found an issue with `vue-template-compiler` has to match exactly the vue version and some breaking changes in vue-loader and laravel-mix webpack config  https://vue-loader.vuejs.org/migrating.html#notable-breaking-changes.

**Comment by dotnetCarpenter** [comment]
I see that _Vue packages version mismatch_ is [a known issue](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/faq.md#why-am-i-seeing-a-vue-packages-version-mismatch-error).

**Comment by JeffreyWay** [comment]
Thanks so much for this PR! I'll review and merge it this week.

**Comment by dotnetCarpenter** [comment]
If anyone wants to check out laravel-mix with babel7 you can include it in a project by
`npm i -D https://github.com/dotnetCarpenter/laravel-mix.git`.

Remember that you can not have 2 laravel-mix in a project, so if it is an existing project then you will have to `npm uninstall --save-dev laravel-mix` first.

**Comment by dotnetCarpenter** [comment]
@JeffreyWay Thank you for being attentive and optimistic about merging this in but giving that this is a breaking change for most people (they might need to upgrade they `.babelrc` and `mix.webpackConfig`), I think it would be wise to get feedback from this community.

In particular my colleague spend 5 minutes with this PR and his vue components failed to render. I pinned it on `vue-loader` but since I'm not updating to v15, as in the migration guide but from v13 to v14, I haven't found any resources that can explain what is going wrong.

**Comment by dotnetCarpenter** [comment]
Hmm.. @JeffreyWay It doesn't seem that the laravel-mix community is stepping up. Perhaps you should merge this in and publish a `3.0.0-beta.1`?

I've seen an issue with `vue-loader` but need more test-cases before I can debug the root cause.

I'm worried that the IT debt of laravel-mix will get too great one day, that upgrading is no longer possible without a huge effort - more that I'm willing to put in as a volunteer.

**Comment by samwrigley** [comment]
Hi @dotnetCarpenter, thank you for all your work on this!

I've tried out `3.0.0-rc.2` on a project and didn't run into any issues and can confirm that all my Vue components complied and rendered correctly.

Please let me know if I can help in any way—I'm very keen to see this merged and released.

**Comment by samwrigley** [comment]
@dotnetCarpenter Having tried installing `@babel/poyfill` to make use of `@babel/preset-env`'s `"useBuiltIns": "usage"` option, I ran into a minor issue when defining my own `.babelrc`:

```
"presets": [
    [
        "@babel/preset-env",
        {
            "useBuiltIns": "usage"
        }
    ]
]
```

I get the following error:

```
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
]
```

Although easy enough to add `'some unique name'`, I was wondering if it might be worth adding it to Laravel Mix itself instead? For example, adding `'laravel-mix'` to lines  [165](https://github.com/JeffreyWay/laravel-mix/blob/a0098f58cd663ba32b9c6877df37660bc8a74a1c/src/config.js#L165) and [174](https://github.com/JeffreyWay/laravel-mix/blob/a0098f58cd663ba32b9c6877df37660bc8a74a1c/src/config.js#L174) of [config.js](https://github.com/JeffreyWay/laravel-mix/blob/a0098f58cd663ba32b9c6877df37660bc8a74a1c/src/config.js) to: 

```
presets: [
    [
        '@babel/preset-env',
        {
            modules: false,
            targets: {
                browsers: ['> 2%']
            },
            forceAllTransforms: true
        },
        'laravel-mix'
    ]
],
plugins: [
    '@babel/plugin-proposal-object-rest-spread',
    [
        '@babel/plugin-transform-runtime',
        {
            helpers: false
        },
       'laravel-mix'
    ]
]
```

Line [168](https://github.com/JeffreyWay/laravel-mix/blob/a0098f58cd663ba32b9c6877df37660bc8a74a1c/src/config.js#L168) might also need changing too:

```
[
    '@babel/plugin-proposal-object-rest-spread',
    {},
    'laravel-mix'
],
```

I might be wrong, but I think this would allow people to more easily set their own preset/plugin options?

**Comment by dotnetCarpenter** [comment]
@samwrigley I just saw this. I'll take a deeper look the next time I get a little time.

In the meantime - wouldn't you normally fix these kind of things in your project `.babelrc` or using `mix.webpackConfig`?

Something similar to, if you want to override the laravel-mix default:
```js
mix.webpackConfig({"rules": [{
              "test": "/\\.js$/",
              "exclude": "node_modules/",
              "use": {
                  "loader": "babel-loader",
                  "options": {
                      "presets": ["@babel/env"],
                      "plugins": [
                          "@babel/polyfill"
                      ]
                  }
              }
            }]
})
```

Sorry if I'm completely off. I'm heading home from office and just saw this.

**Comment by pahan35** [comment]
Hi, @dotnetCarpenter. Your work is awesome!

I tried to use your build in production and noticed that after updates there appears comment lines from vendor packages like React etc
image

Adding next lines on mix init helps me to avoid it, but I guess it should be somewhere inside
```
mix.options({
  uglify: {
      uglifyOptions: {
        output: {
          comments: false,
        },
      },
    }
});

```

**Comment by JeffreyWay** [comment]
I have this merged on the v3 branch. Can some of you try it out on a fresh or existing app? If you experience any compile issues, please let me know.

```
npm remove laravel-mix
npm install git://github.com/JeffreyWay/laravel-mix.git#v3
npm run dev
```

If upgrading an existing app, don't forget @dotnetCarpenter's upgrade notes.

- In package.json, change all occurrences of "babel-plugin-[name]": "6.x" to "@babel/plugin-[name]": "7.x"
- In .babelrc change all occurrences of plugins to version 7 , e.i."plugins": ["babel-plugin-transform-object-rest-spread"] to "plugins": ["@babel/plugin-proposal-object-rest-spread"]

**Comment by azdanov** [comment]
Didn't encounter any issues.

My project is quite simple though:

`package.json`
```json
"devDependencies": {
    "algoliasearch": "^3.30.0",
    "braintree-web-drop-in": "^1.14.1",
    "cross-env": "^5.1",
    "instantsearch.js": "^2.10.4",
    "laravel-mix-purgecss": "^3.0.0",
    "laravel-mix-tailwind": "^0.1.0",
    "tailwindcss": "^0.7.2",
	"laravel-mix": "git://github.com/JeffreyWay/laravel-mix.git#v3"
}
```

`webpack.mix.js`
```js
const mix = require("laravel-mix");
require("laravel-mix-tailwind");
require("laravel-mix-purgecss");

mix.extract([
    "braintree-web-drop-in",
    "algoliasearch",
    "instantsearch.js",
    "instantsearch.js/es/widgets"
])
    .js("resources/js/app.js", "public/js")
    .sass("resources/sass/app.scss", "public/css")
    .tailwind()
    .version()
    .purgeCss({
        whitelistPatternsChildren: [/^ais-search-box/, /^ais-hits/]
    })
    .disableNotifications();
```

```txt
 DONE  Compiled successfully in 21937ms                 9:04:16 PM

          Asset       Size  Chunks                    Chunk Names
  /js/vendor.js     740 kB       0  [emitted]  [big]  /js/vendor
     /js/app.js      10 kB       1  [emitted]         /js/app
/js/manifest.js  799 bytes       2  [emitted]         /js/manifest
   /css/app.css    22.8 kB       1  [emitted]         /js/app
```

**Comment by vinkla** [comment]
I've tried running this in two local projects without any issues. Good work @dotnetCarpenter!

**Comment by securit** [comment]
Thought I'd give it a whirl with something a bit more complex.... no problems here. Looks good.
```json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-regular-svg-icons": "^5.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@fortawesome/pro-light-svg-icons": "^5.2.0",
    "@fortawesome/pro-regular-svg-icons": "^5.2.0",
    "@fortawesome/pro-solid-svg-icons": "^5.2.0",
    "@fortawesome/vue-fontawesome": "^0.1.2",
    "axios": "^0.18",
    "bootstrap": "^4.1.1",
    "bootstrap-confirmation2": "^4.0.1",
    "bootstrap-daterangepicker": "^2.1.30",
    "chart.js": "^2.7.2",
    "cross-env": "^5.2.0",
    "datatables.net-autofill-dt": "^2.3.2",
    "datatables.net-buttons-dt": "^1.5.4",
    "datatables.net-colreorder-dt": "^1.5.1",
    "datatables.net-dt": "^1.10.19",
    "datatables.net-editor": "^1.6.5",
    "datatables.net-editor-dt": "^1.6.3",
    "datatables.net-fixedcolumns-dt": "^3.2.6",
    "datatables.net-fixedheader-dt": "^3.1.5",
    "datatables.net-keytable-dt": "^2.5.0",
    "datatables.net-rowgroup-dt": "^1.1.0",
    "datatables.net-rowreorder-dt": "^1.2.5",
    "datatables.net-scroller-dt": "^1.5.1",
    "datatables.net-select-dt": "^1.2.7",
    "font-awesome": "^4.7",
    "glob": "^7.1.2",
    "gulp-sass": "^4.0.1",
    "imagemin": "^6.0.0",
    "jquery": "^3.2",
    "jquery-ui-dist": "^1.12.1",
    "laravel-mix": "git://github.com/JeffreyWay/laravel-mix.git#v3",
    "laravel-mix-purgecss": "^2.2.3",
    "leaflet": "^1.3.4",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "lodash": "^4.17.5",
    "minimatch": "^3.0.4",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "network-js": "^2.1.0",
    "notify-send": "^0.1.2",
    "npm": "^6.3.0",
    "npm-registry-fetch": "^3.8.0",
    "pdfkit": "^0.8.3",
    "pdfmake": "^0.1.38",
    "popper.js": "^1.14.4",
    "promise": "^8.0.1",
    "rtlcss": "^2.4.0",
    "suitcss": "^3.0.0",
    "sweetalert2": "^7.26.11",
    "three": "^0.98.0",
    "unsupported": "^1.1.0",
    "urijs": "^1.19.1",
    "vue": "^2.5.15",
    "vue-datatables-net": "^1.0.1",
    "vue-datepicker-local": "^1.0.12",
    "vue-json-pretty": "^1.4.1",
    "vue-select": "^2.5.1",
    "vue2-daterange-picker": "^0.1.1",
    "vue2-leaflet": "^1.0.2",
    "yarn": "^1.10.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6",
    "@fortawesome/fontawesome-pro": "^5.2.0",
    "laravel-mix-tailwind": "^0.1.0",
    "purgecss": "^0.21.0",
    "tailwindcss": "^0.6.5"
  },
  "version": "1.9.4"
}
```

**Comment by JeffreyWay** [comment]
Thanks, everyone!

**Comment by msonowal** [comment]
@JeffreyWay 
Any idea how to get work with `babel-plugin-syntax-dynamic-import`
Currently I have this

`package.json`
anyone can upgrade to v3

```{
  "name": "my-some-project",
  "version": "0.0.2",
  "description": "A SPA for some-project",
  "author": "Manash Jyoti Sonowal <manash149@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot-secure": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --https --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --profile --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "silent": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --config=node_modules/laravel-mix/setup/webpack.config.js",
    "svg": "vsvg -s ./resources/assets/revamped/svg/src -t ./resources/assets/revamped/svg/icons"
  },
  "dependencies": {
    "@sentry/browser": "4.2.1",
    "@tweenjs/tween.js": "^17.2.0",
    "animate.css": "^3.7.0",
    "axios": "^0.18.0",
    "buefy": "^0.7.0",
    "bulma": "^0.7.2",
    "bulma-badge": "^2.0.0",
    "bulma-divider": "^2.0.1",
    "firebase": "^4.11.0",
    "font-awesome": "^4.7.0",
    "idle-js": "^0.1.3",
    "laravel-echo": "^1.4.0",
    "lodash": "^4.17.10",
    "moment-duration-format": "^1.3.0",
    "moment-timezone": "^0.5.14",
    "socket.io-client": "^2.1.1",
    "vue": "^2.5.17",
    "vue-analytics": "^5.16.0",
    "vue-ctk-date-time-picker": "^1.2.1",
    "vue-echo-laravel": "^0.0.4",
    "vue-i18n": "^7.6.0",
    "vue-js-popover": "^1.1.7",
    "vue-json-excel": "^0.2.1",
    "vue-lightbox": "^1.1.6",
    "vue-rate-it": "^2.1.0",
    "vue-router": "^3.0.1",
    "vue2-canvas-gauges": "^0.0.0",
    "vue2-datepicker": "^2.6.0",
    "vue2-filters": "^0.3.0",
    "vuefire": "^1.4.5",
    "vuelidate": "^0.7.4",
    "vuelidate-error-extractor": "^1.3.0",
    "vuetable-2": "^1.7.5",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "browser-sync": "^2.26.3",
    "browser-sync-webpack-plugin": "^2.2.2",
    "cross-env": "^5.2.0",
    "laravel-mix": "^2.1.14",
    "vue-svgicon": "^3.2.1",
    "webpack-bundle-analyzer": "^3.0.3"
  }
}
```

any my .babelrc

```
{
    "plugins": ["syntax-dynamic-import"]
}
```

**Comment by azdanov** [comment]
@msonowal Try [@babel/plugin-syntax-dynamic-import](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import).

**Comment by msonowal** [comment]
> @msonowal Try [@babel/plugin-syntax-dynamic-import](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import).

Did Not work thats why I posted

**Comment by azdanov** [comment]
What is the error?

**Comment by dotnetCarpenter** [comment]
@msonowal Can you post your _webpack.mix.js_ and error message?

**Comment by ovac** [comment]
I keep running into this problem no matter what I do. Any ideas?

```
...
ERROR in ./resources/assets/js/app.js
Module build failed: Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ] 

...
```

**Comment by dotnetCarpenter** [comment]
>Error: Duplicate plugin/preset detected.

@ovac Looks like you got the same babel plugin define multiple times. :smile: 

You have to:
1. at least name the plugin, from your error message. - So we know if it's included in laravel-mix 3.0
2. at least post your _webpack.mix.js_
3. post your babel config, if you have one (_.babelrc_ or _.babelrc.js_)
4. and maybe even your babel/webpack dependencies from your _package.json_

**Before anyone can help you.**

PS. And remember version numbers on everything.

**Comment by ovac** [comment]
.babelrc
```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-transform-react-jsx"
    ]
}
```

package.json
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@babel/core": "^7.0.0",
        "@babel/plugin-proposal-class-properties": "^7.0.0",
        "@babel/preset-react": "^7.0.0",
        "@playlyfe/gql": "^2.6.0",
        "axios": "^0.18",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^3.0",
        "lodash": "^4.17.5",
        "react": "^16.5.2",
        "react-dom": "^16.5.2"
    }
}
```

**Comment by adriandmitroca** [comment]
@ovac 

Looks like Mix adds @babel/preset-env behind the scenes and you're trying to add the second instance. You should remove preset-env from your custom set up.

https://github.com/JeffreyWay/laravel-mix/blob/03cbfc7102a58f5d16c95c72b9b76f92c6dba8fd/src/config.js#L145

**Comment by ovac** [comment]
I did this already and I still get the same error @adriandmitroca

**Comment by adriandmitroca** [comment]
@ovac 

Try to remove `@babel/plugin-proposal-object-rest-spread` plugin as well, this one is added by Mix as well.

**Comment by dotnetCarpenter** [comment]
@ovac I'm confused to why you have any of the presets and is not just using
`mix.react()` but I'll have to do a quick setup on my machine before I can
see what's really going on.

**Pull request merged**
