### PR TITLE
Remove wrong information about jQuery autoloading

### LINKED ISSUE #615: jQuery no longer autoloaded by default despite docs stating otherwise
This is pretty self-explanatory but the 0.9.0 docs (specifically https://github.com/JeffreyWay/laravel-mix/blob/v0.9.0/docs/autoloading.md) state that 

> ...jQuery autoloading is shipped out of the box...

However, it's been removed from the Mix.autoload config in https://github.com/JeffreyWay/laravel-mix/blob/v0.9.0/setup/webpack.config.js#L299

### PR DESCRIPTION
**Pull request by manniL**
Remove the information that jQuery is still being autoloaded by Laravel Mix and added a short paragraph that the behaviour changed. Fix #615

### CODE REVIEW

**Comment by JeffreyWay** [comment]
I'd rather not declare that it used to be supported but isn't. I'll remove the section entirely.

**Comment by manniL** [comment]
@JeffreyWay I see your point there. Anyway, for people that used 0.8.x before this could be a really important information, because code can break (like it happened to me :smile:)

**Comment by JeffreyWay** [comment]
I did put in the release notes, so hopefully that should be enough.

**Comment by manniL** [comment]
Couldn't find a changelog or release notes file in the repository. Could you give me a link?

**Comment by JeffreyWay** [comment]
https://github.com/JeffreyWay/laravel-mix/releases/tag/v0.9.0

**Comment by manniL** [comment]
Oh :man_facepalming: Thank you!

**Pull request closed without merging**
