### PR TITLE
Feature/override and merge rules

### PR DESCRIPTION
**Pull request by tpraxl**
Some use cases require modifications of existing webpack rules. It's no problem to add rules, but you can currently not reliably modify existing rules (except for hacks that might break in the future).

Related issues:

* #1423 (in my opinion, the most important one, because quill shouldn't be in the 20% use cases not supported by laravel-mix)
* #1397 (also an important one: CKEditor)
* #997 
* #949
* #942
* #374

This PR allows the user to replace, merge and skip the existing rules like this:

```js
// Skip rule
Mix.customizeRule.fonts = (rule, Config) => ({})
```

```js
// Replace rule
Mix.customizeRule.images = (rule, Config) => ({
    // completely replaces the original rule
    test: /\.png$/,
    loaders: [
      {
        loader: 'html-loader',
        options: {
          minimize: true
        }
      }
    ]
});
```

```js
// merge with own rules
Mix.customizeRule.images = (rule, Config) => {
    // only replace the test
    rule.test = /\.png$/;
    // add an exclude configuration
    rule.exclude = /node_modules\/quill\/assets\/icons\/(.*)\.svg$/;
    // and add a loader
    rule.loaders.push(myLoader);
    // the remaining original rule's configuration stays the same 
    return rule;
};
```

The "SVG images in font-folder" discussions would have been pointless if we had had this feature before.

Part of this PR is the restructuring of rules into their own respective files. See `src/rules` for all webpack rules used by laravel-mix (except dynamic preprocessor rules).

The user can hook into the rules by referring to their (file)names: `Mix.customizeRule[theRuleName]` and providing a closure for it. Mix will look up any defined closures and replace the prepared rule with the user defined rule.

I think this feature is important and we could very well raise "[80% of the use cases](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/basic-example.md)" to 90% after merging this PR. 

So, I'm very motivated to continue working on it until possible doubts are resolved. 

Don't hesitate to ask for refinement.

[edit] corrected minor typo
[edit] added CKEditor issue

### CODE REVIEW

**Comment by tpraxl** [comment]
This PR needs to be updated if/when #1467 gets merged.

**Comment by tegola** [comment]
The `Mix.customizeRule.rulename = () => {}` looks a bit out of place in Mix. A more familiar syntax would look better and easier to understand. Something like `Mix.customizeRule('ruleName', (rule, Config) => {})`.

Also, new users reach out for Laravel Mix because webpack initial setup looks very confusing, and having them learn that `Mix` (the class) and `mix` (the instance in the docs) are different entities isn't ideal. Does `customizeRule` be used on the instance?

Again, great work.

**Comment by ZapevalovAnton** [comment]
Yes, ```Mix``` and ```mix``` are misleading. Moreover ```Mix``` is not imported explicitly in the ```webpack.mix.js``` file. Maybe it is possible to use the version of @tegola ?

**Comment by tpraxl** [comment]
Thanks for your feedback. I'll take your proposals into account (weird syntax and `mix` instead of `Mix`) and will update this PR asap.

**Comment by tpraxl** [comment]
Sorry, didn't have the time to come back to this PR yet. It should still be considered active though.

**Comment by tpraxl** [comment]
Added the option to use the syntax, suggested by @tegola and @ZapevalovAnton:

```js
mix.customizeRule('images', (rule, Config) => {});
```

**Comment by tpraxl** [comment]
I reckon this PR is not going to be merged, having watched [this screencast](https://laracasts.com/series/whatcha-working-on/episodes/27). From what I've got so far, the idea of splitting it up into components is far better than just overriding rules – given the components can be dynamically added and their rules overridden. It fits into an idea I had while I prepared this PR: "recipes" for mix / webpack aspects.

**Comment by tegola** [comment]
I'm not a subscriber, I can't see that screencast, sorry.

**Comment by tpraxl** [comment]
@tegola see [the comparison between the branch he's working on with master](https://github.com/JeffreyWay/laravel-mix/compare/master...components)

**Comment by tegola** [comment]
Aaaah bummer. Let's see how it turns out. Thanks.

**Comment by tpraxl** [comment]
This PR conflicts with the plugin concept of laravel that has been developed in parallel or slightly later. I'll close it.

**Comment by PayteR** [comment]
@tpraxl is there any documentation, how to substitute default components with my custom components? https://github.com/JeffreyWay/laravel-mix/issues/1616

**Comment by raphaelsaunier** [comment]
I think an alternative, probably more convenient solution would be to use [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain) (have a look at the [vue-cli docs](https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md) to see how it can be used) but I realise it would require some significant changes to the overall architecture of Laravel Mix.

---

Either way, if it helps anyone, here's how I ended up overriding the generated rules to correctly compile [quill.js](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/), which didn't work out of the box with Mix:

```js
mix.extend('quill', webpackConfig => {
    const { rules } = webpackConfig.module;

    // 1. Exclude quill's SVG icons from existing rules
    rules.filter(rule => /svg/.test(rule.test.toString()))
        .forEach(rule => rule.exclude = /quill/);

    // 2. Instead, use html-loader for quill's SVG icons
    rules.unshift({
        test: /\.svg$/,
        include: [path.resolve('./node_modules/quill/assets')],
        loaders: [{ loader: 'html-loader', options: { minimize: true } }]
    });

    // 3. Don't exclude quill from babel-loader rule
    rules.filter(rule => rule.exclude && rule.exclude.toString() === "/(node_modules|bower_components)/")
        .forEach(rule => rule.exclude = /node_modules\/(?!(quill)\/).*/);
});

// …

mix.js(/* ... */)
   .quill()
```

**Pull request closed without merging**
