### PR TITLE
Vue loader updated

### PR DESCRIPTION
**Pull request by pavinthan**
Vue loader updated

### CODE REVIEW

**Comment by pavinthan** [comment]
Thank you guys 👍

**Comment by askaoru** [comment]
I'm not too sure which are at fault here but i'm getting the error and I think it's kinda related to this PR.
```
Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.9

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

I'm using laravel-mix 1.7.2

**Comment by ruchern** [comment]
@askaoru Your issue is with `vue-template-compiler` and not `vue-loader`

Just run `npm install -D vue-template-compiler@latest` or yarn and you will be fine.

**Comment by askaoru** [comment]
Thanks @ruchern .
But for some reason I need to include both
`"vue-template-compiler": "^2.5.13"` and `"vue-loader": "^13.6.1"`.

Just adding the latest `vue-template-compiler` gave me a `Module not found: Unable to resolve vue-loader`, which is pretty odd. I'll take a look later if there's any conflict my other libraries.

**Comment by ruchern** [comment]
@askaoru That is indeed weird but your method does solve the problem.

**Pull request closed without merging**
