### PR TITLE
Upgrade vue-loader to v14

### PR DESCRIPTION
**Pull request by ruchern**
## This is a work in progress to support `vue-loader` v14

Due to a breaking change from `vue-loader`, `CommonJS` or `require()` is no longer supported. Users are recommended to use ESM for future releases of `vue-loader`. See https://github.com/vuejs/vue-loader/issues/1172#issuecomment-372488772

Signed-off-by: Ru Chern Chong <me@ruchern.com>

### CODE REVIEW

**Comment by ruchern** [comment]
@JeffreyWay @ankurk91 this is weird, I am unable to produce the problem on `Laravel 5.6` with `vue-loader@14.2.1`. Can you guys pull this PR and see if you guys can reproduce the problem in #1524

**Comment by ankurk91** [comment]
Please also remove any reference to `esModule` config

**Comment by ankurk91** [comment]
You are using `yarn` but repo is using `npm` .
You need to update both lock files.
Or just keep nom lock file.

**Comment by ruchern** [comment]
Let me retry with `npm`

**Comment by ruchern** [comment]
Looks like we have to force people to use ESM as per Evan You's comment here:  https://github.com/vuejs/vue-loader/issues/1172#issuecomment-372488772

**Comment by ruchern** [comment]
@JeffreyWay any comment on this while waiting for the Webpack v4 to be merged?

**Comment by JeffreyWay** [comment]
I can't merge this until we do a new major release of Mix. And even then, a lot of people will choose not to update, because they can't suddenly switch their codebase over to ESM's without performing a number of manual updates. 

So I need to hold off on this for a bit, until we decide what to do. At the very least, the laravel/laravel repo will need to be updated to remove the old commonjs requires.

**Comment by ankurk91** [comment]
@ruchern 
`vue-style-loader` will be auto install by `vue-loader` automatically

https://github.com/vuejs/vue-loader/blob/f06e3e7d010f0bcecc1aaac66af6d312e09e86bc/package.json#L57

is there any reason behind specifying `vue-style-loader` separately as laravel-mix dependency ?

**Comment by ruchern** [comment]
`vue-style-loader` was automatically installed when I upgrade `vue-loader` using `npm install -D vue-loader@latest`

**Comment by ankurk91** [comment]
Vue loader v15 to have more breaking changes
https://github.com/vuejs/vue-loader/tree/next

Second beta has been released

**Comment by ruchern** [comment]
@ankurk91 I saw Evan's tweet on `vue-loader` v15 and I was like, here we go again.

**Comment by ruchern** [comment]
@JeffreyWay @ankurk91 I will go ahead and close this PR since v15 is imminent and no point releasing 2 major updates.

**Pull request closed without merging**
