### PR TITLE
Allow use of preprocessors + CSS modules in .vue files

### LINKED ISSUE #2370: Can't get vue sass modules to work
-   Laravel Mix Version: 5.0.4
-   Node Version: v12.14.1
-   NPM Version: 6.13.4
-   OS: Windows 10

### Description:

I can't get my assets to compile properly when using vue sass modules. I either get an error during compilation or the scss within the vue component is treated as standard scss as opposed to a scss module that should only apply to the component in which it is defined.

My current project uses `laravel-mix v3.0.0` and I am trying to upgrade to `v5.0`. With `v3.0.0` I do not have to add any configuration to `webpack.mix.js`, both css and sass modules work fine right out of the box. Apparently this is no longer the case as of `v4.0`. I see in the `v4.0` release notes that the sass dependencies are no longer included by default but there is no mention of webpack configuration.

I created a fresh, minimal laravel 7.x installation to reproduce the problem and rule out any causes related to my existing project.

Here is the link to the repo:
https://github.com/brianrlewis/laravel-vue-sass-modules-problem

I've tried many different webpack configurations inside `webpack.mix.js` without any success.

### Steps To Reproduce:

1. Clone this repo: https://github.com/brianrlewis/laravel-vue-sass-modules-problem
2. npm install
3. npm run dev
4. composer install
5. php artisan serve

When you get to step 3 you should get this error:

```
ERROR in ./resources/js/WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./node_modules/vue-style-loader!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
4 │ var content = require("!!../../node_modules/sass-loader/dist/cjs.js!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true&");
```

If you uncomment this at the bottom of `webpack.mix.js` you will get a different error.
`//   .sass('resources/sass/app.scss', 'public/css');`

To get to steps 4 and 5 you can comment out the following in `webpack.mix.js` which will allow a successful build.

```
            {
                test: /\.scss$/,
                use: [
                  'vue-style-loader', // 'style-loader' doesn't work either
                  'css-loader',
                  'sass-loader'
                ],
            }
```

After you load the site you can see that the sass inside `resources/js/WhyYouNoWork.vue` gets applied to the entire site globally as opposed to only styling `<div :class="$style.wrapper">`. I'm assuming this is simply because `sass-loader` has to be added to the webpack config in order for this to work.

Using css modules works fine, just not scss modules.

Any ideas on how to get this to work? 

I've tried everything listed here, plus a dozen other sass-loader config variations.
https://vue-loader.vuejs.org/guide/pre-processors.html

### PR DESCRIPTION
**Pull request by thecrypticace**
Closes #2370

@JeffreyWay Do you want me to back port this to Mix v5 or leave it for Mix v6 only?

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Let's hold off for now.

**Comment by nmfzone** [comment]
How to get this working with React and `module.scss`? Any clue?

I've tried it, but get no luck.

**Comment by thecrypticace** [comment]
Can you give an example of what you're doing and what you expect the result to be? (A reproduction repo + readme/instructions would help the most). When I test React + CSS modules it works as I expect (see: https://github.com/JeffreyWay/laravel-mix/pull/2732/commits/e0f2fba7df1b893a2c69fbe32a63593175ba0070)

**Comment by nmfzone** [comment]
@thecrypticace Here it's https://github.com/nmfzone/laravel-mix-repro.

**Comment by nmfzone** [comment]
@thecrypticace Ah, I found the problem. So, the css module is generated in the js folder (public/js), and I don't include it on my blade views. Is it possible to change the css module output file (extracted by mini-css-extract-plugin i guess)?

**Comment by thecrypticace** [comment]
Oh that's odd. When I import them I don't get an extra CSS file. It's included in the JS file: 

Screen Shot 2021-01-02 at 20 48 57

I'll have to look further into it.

**Comment by thecrypticace** [comment]
@nmfzone I figured out the issue. It will be fixed whenever the next version of Mix is released.

**Comment by nmfzone** [comment]
@thecrypticace Awesome. But how about change the output of the extracted css? It seems that it's good to extract the css, but change the output to the `public/css`.

**Comment by nmfzone** [comment]
It seems that Vue support that (change the extract path) https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Vue.js#L172. It's good to see that feature in React too I guess.

**Comment by thecrypticace** [comment]
Yeah, we should allow it to be configured globally for all css. Not just as a Vue feature.

**Pull request merged**
