### PR TITLE
Feature/automated testing for pull requests

### PR DESCRIPTION
**Pull request by tpraxl**
# Allow for automated testing of pull requests

The tests are not only run on **Linux** + **OSX**, but also on **Windows**, with the help of AppVeyor. 

* This helps to prevent laravel-mix from breaking on one of these systems (given the coverage is sufficient)
* forces contributors to support the other platforms 
* and creates confidence in PR changes

The PR not only contains the configurations for [Travis CI](https://travis-ci.org/) and [AppVeyor](https://www.appveyor.com/) but also **fixes**

* old test failures on windows
* randomly failing tests
* and one failing test, that was introduced in one of the latest merges (see commit history of this PR for details).

Note that the `test` script has been changed in `package.json` for two reasons:

* `sudo` isn't required to run nyc or ava
* `--serial` is used to prevent filesystem race conditions and thus randomly failing tests (Test A creates a file, Test B picks it up, Test A deletes it while Test B reads it)

The commit messages often contain details to explain why a certain change was made.

In order to automate the tests, you need to configure the github project: 

## Travis CI

`Settings -> Integrations & Services -> Add service -> Travis CI`

## AppVeyor

You need to create an account. Like Travis CI, this is free for open source projects. 

You then need to add your project via `+ New Project -> GitHub -> laravel-mix`. In the process, AppVeyor will setup the webhook (`Settings->Webhooks: https://ci.appveyor.com/api/github/webhook (pull_request and push)`) in GitHub for you.

## Example reports

* Travis CI: https://travis-ci.org/tpraxl/laravel-mix/builds/331173523
* AppVeyor: https://ci.appveyor.com/project/tpraxl/laravel-mix/build/1.0.32

Thanks to @kohenkatz, who helped a lot with fixing issues and failing tests on windows (see #1383).

Notice that [OSX builds currently have very long delays on Travis CI](https://www.traviscistatus.com/). It took almost 7 hours until all the OSX instances have started for the last commit. This should be a temporary issue though.

### CODE REVIEW

**Comment by tpraxl** [comment]
Just fixed the broken tests, introduced by merging #1426 and restored the yarn.lock.

**Comment by tpraxl** [comment]
@ruchern I'm fine with keeping both or choosing one. The only thing is: laravel-mix supports node 6 and we had trouble testing node 6 on windows with npm, because AppVeyor's environment for node 6 comes with a version of npm that doesn't respect the package.log. This breaks the same test that was broken during the latest library updates. See [this issue for details](https://github.com/tpraxl/laravel-mix/issues/3#issuecomment-359046954). 

So I chose to use yarn for testing on AppVeyor. I would have to find another way testing node 6 on windows with deterministic test data, should there be a decision for removing `yarn.lock`.

**Comment by ruchern** [comment]
I see. Thank you for the input on AppVeyor's issue with Windows. I did not know that for sure since I run on macOS and Linux only.

**Comment by JeffreyWay** [comment]
Going over this now. Thanks!

**Comment by tpraxl** [comment]
Note that the tests currently fail because of the latest commits

**Comment by tpraxl** [comment]
See [Travis CI](https://travis-ci.org/tpraxl/laravel-mix/jobs/332346812) and [AppVeyor](https://ci.appveyor.com/project/tpraxl/laravel-mix/build/job/yaty8nr6yu281xnt). I have started a build on a test branch that contains the latest commits.

**Comment by JeffreyWay** [comment]
Yep, I have that fixed. I've also activated Travis and AppVeyor.

Excellent work here, @tpraxl. And thanks so much for the useful description. Big help. :)

**Comment by tpraxl** [comment]
You are welcome. Thanks for merging.

**Comment by MohannadNaj** [comment]
Awesome 😍

**Pull request merged**
