### PR TITLE
Instruct AppVeyor to run npm install rather than npm ci

### LINKED ISSUE #2401: AppVeyor fails on npm ci
-   Laravel Mix Version (`npm list --depth=0`): 5.0.4
-   Node Version (`node -v`): 6.14.4
-   NPM Version (`npm -v`): 10.20.0
-   OS: WSL @ Ubuntu 18.04

### Description:
AppVeyor is failing builds when running `npm ci` because it expects a lock file to exist. Lock files generally aren't committed to libraries, so it may make sense to run `npm install` instead if Mix isn't committing a lock file (i.e. it is ignored by `.gitignore`).

### Steps To Reproduce:
1. Raise a PR based on master
2. Observe that AppVeyor will fail the build due to `npm ci` not finding `package-lock.json`

### PR DESCRIPTION
**Pull request by glennmcewan**
Fixes #2401

### CODE REVIEW

**Comment by glennmcewan** [comment]
Possibly fixed in #2303

**Comment by thecrypticace** [comment]
Hah yeah I fixed that in the webpack 5 PR

**Comment by glennmcewan** [comment]
Ah lovely, thanks @thecrypticace! Is it suppposed to still be failing?

Also...Travis CI - jobs seem to be running but not reporting back to GH PRs if you know anything about that?

**Comment by thecrypticace** [comment]
Yeah there's one failing test on Windows at the moment related to public path normalization. I thought I fixed it but alas the fix wasn't the right one. Gotta put this on my windows machine and tackle it there. I do not know why Travis is not reporting to GitHub.

cc @JeffreyWay The repo settings might need some tweaking so Travis can report back.

**Comment by glennmcewan** [comment]
Okay, great. Thanks for that! Noticed some strange things around AppVeyor/Travis tests when it comes to line endings. SASS tests work in Travis, but fail in AppVeyor... #2400

**Pull request closed without merging**
