### PR TITLE
Use ModuleGraph.getIssuer instead of Module.issuer

### LINKED ISSUE #2767: [6.x] Errors with SVG Spritemap Webpack Plugin: 'There was no ModuleGraph assigned to the Module for backward-compat'
-   Laravel Mix Version: 6.0.9 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.1
-   NPM Version (`npm -v`): 6.14.10
-   OS: Mac 10.15.7

### Description:

> So to conclude, IMO the code in laravel-mix should be updated to use the new ModuleGraph, they might have a plan for that since laravel-mix isn't stable yet w.r.t. Webpack 5 support yet. Feel free to create an issue on their side and reference this thread. I'm closing this one and am definitely open for a further discussion if any ideas for workarounds pop up.

See https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/132#issuecomment-724928222

### Steps To Reproduce:

Reproduces with https://github.com/danielbachhuber/laravel-mix-2767

```
npm run prod

> laravel-mix-svg-spritemap@1.0.0 prod /Users/danielbachhuber/projects/laravel-mix-svg-spritemap
> npm run production


> laravel-mix-svg-spritemap@1.0.0 production /Users/danielbachhuber/projects/laravel-mix-svg-spritemap
> mix --production

75% sealing chunk optimization SplitChunksPlugin/Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack/lib/ModuleGraph.js:676
					throw new Error(
					^

Error: Module.issuerThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack/lib/ModuleGraph.js:676:12
    at Function.getModuleGraphForModule (/Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack/lib/ModuleGraph.js:667:18)
    at RawModule.get issuer [as issuer] (/Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack/lib/Module.js:274:22)
    at Chunks._checkTest (/Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/laravel-mix/src/Chunks.js:205:20)
    at /Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/laravel-mix/src/Chunks.js:168:38
    at Array.every (<anonymous>)
    at /Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/laravel-mix/src/Chunks.js:168:19
    at /Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack-merge/dist/join-arrays.js:40:38
    at /Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack-merge/dist/join-arrays.js:40:38
    at checkTest (/Users/danielbachhuber/projects/laravel-mix-svg-spritemap/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:482:10)
```

### PR DESCRIPTION
**Pull request by thecrypticace**
It's been deprecated. This should fix #2767. I'll do some testing later this evening.

cc @danielbachhuber

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @thecrypticace !

I don't know these internals at all but let me know if there's anything I can do to help further.

**Comment by danielbachhuber** [comment]
@thecrypticace Did this fix it?

**Comment by thecrypticace** [comment]
@danielbachhuber It did!

**Comment by danielbachhuber** [comment]
@thecrypticace I've confirmed the fix — works great! When do you think you'll tag the next release?

**Pull request merged**
