### PR TITLE
Added support for es7 async/await

### PR DESCRIPTION
**Pull request by lkmadushan**
With this feature you can write asynchronous functions synchronous way, you don't need promises.

```
async status() {
    try {
        let { data } = await axios.get('status');
        console.log(data);
    catch(err) {
        console.log(err);
    }
}
```

### CODE REVIEW

**Comment by ankurk91** [comment]
We may also want "babel plugin dynamic import"

**Comment by lkmadushan** [comment]
@ankurk91 Actually I don't know why do we need that? Anyway this is working fine.

**Comment by JeffreyWay** [comment]
Does anyone have an argument for why this shouldn't be merged? If not, I'll pull it in.

**Comment by ankurk91** [comment]
@lkmadushan 
Please rebase to fix merge conflicts.

**Comment by lkmadushan** [comment]
fixed failing tests

**Pull request merged**
