### PR TITLE
Severity vulnerability fixes

### PR DESCRIPTION
**Pull request by subotkevic**
## 1. Just some light severity vulnerabilities fixes.

Just the `npm audit fix` command to correctly light-fix everything.

## 2. Upgraded `webpack-dev-server` to `3.1.10` to fix high severity vulnerability (Missing Origin Validation)

Versions of webpack-dev-server before 3.1.6 are missing origin validation on the websocket server. This vulnerability allows a remote attacker to steal a developer's source code because the origin of requests to the websocket server that is used for Hot Module Replacement (HMR) are not validated.

Source: https://www.npmjs.com/advisories/725

**Important upgrade notes:**
Drops support for Node.js v4.

Source: https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0-beta.1

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Thank you!

**Comment by JeffreyWay** [comment]
@subotkevic  Did you check to see if this works before submitting a PR? I thought webpack-dev-server 3.0 doesn't support webpack 3 and below, which we're still on.

**Comment by subotkevic** [comment]
> @subotkevic Did you check to see if this works before submitting a PR? I thought webpack-dev-server 3.0 doesn't support webpack 3 and below, which we're still on.

Well, webpack-dev-server 3 only adds support for Webpack 4, but it's not dropping support for Webpack 3.

I have tested it in action, and of course `npm run test` succeeded. Only the #1807 part was failing, which looks fixed already on that PR.

Everything works fine, just AppVeyor tests are failing for some reason. Not yet sure why.

**Comment by JeffreyWay** [comment]
I haven't yet tested this, but according to the 3.0 release notes, it doesn't provide support for webpack 3.

https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0

> Breaking change: webpack v4 is now supported. Older versions of webpack are not supported.

**Comment by subotkevic** [comment]
Ok, looks like I've read wrong release notes...

**Comment by subotkevic** [comment]
@JeffreyWay but we still need to upgrade then, because the issue exists on webpack-dev-server 2. And it's deprecated.

**Comment by NiltonMorais** [comment]
npm install -g npm@5.6.0 solved for me

**Comment by lachieh** [comment]
> npm install -g npm@5.6.0 solved for me

This just removes the warning about the security issue. It does not solve it. Do not do this.

**Pull request merged**
