### PR TITLE
GH-2890: make sure ts chunks are exported under public/js

### LINKED ISSUE #2890: Typescript chunks are created under `public` folder, not `public/js`
-   Laravel Mix Version: 6.0.13 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.0.0
-   NPM Version (`npm -v`): 7.6.3
-   OS: MacOs Catalina 10.15.3

### Description:
I have a react typescirpt project. When dynamically import components, the js chunks file are created directly under `public/`.
Just replacing the project with a js one with the same components, the js chunks files are created under `public/js/` folder.

### Steps To Reproduce:
```
mix
  .ts('resources/js/index.tsx', 'public/js/app.js')
  .react()
```

### PR DESCRIPTION
**Pull request by aarbi**
fixes #2890

### CODE REVIEW

**Comment by aarbi** [comment]
I haven't found a combination between react and typescripts tests. I would appreciate some guidance about the approach you want to follow to add a test for this PR

**Comment by thecrypticace** [comment]
Thanks @aarbi!

**Comment by aarbi** [comment]
thanks @thecrypticace for pushing the tests!
there is one failure in Actions regarding windows though :/

**Comment by thecrypticace** [comment]
Yeah it's an unrelated spurious failure. It crops up sometimes. Wish I knew why. :/

**Pull request merged**
