### PR TITLE
Fix  react-refresh in React Component

### PR DESCRIPTION
**Pull request by soilSpoon**
This is because when you enable overlay, you get websocket related errors.

I hope to re-enable after resolving this.

image

## Update
`@pmmmwh/react-refresh-webpack-plugin` was updated to the `^0.5.0-beta.0` version that supports `webpack-dev-server` `4.0.0-beta.0`, and solve the phenomenon that `hmr` does not work normally when using react components

### CODE REVIEW

**Comment by thecrypticace** [comment]
Could we figure out why the websocket url is invalid (I think it's missing the ws:// prefix) and fix that instead? If not then yeah we can merge this in.

**Comment by soilSpoon** [comment]
I'll try it once on the weekend

**Comment by soilSpoon** [comment]
@thecrypticace I fixed it!

**Comment by soilSpoon** [comment]
Fixed it!

**Comment by soilSpoon** [comment]
@JeffreyWay Could you please let me know when the changes in the PR will be reflected?

**Comment by JeffreyWay** [comment]
@soilSpoon The plan is to push a tagged release out this weekend.

**Pull request merged**
