### PR TITLE
[ON HOLD] Support for webpack 4

### PR DESCRIPTION
**Pull request by thecrypticace**
### This is currently blocked by an issue with webpack 4 regarding CSS chunk splitting.

**All but one test currently pass.**

---

I've gathered some data on which plugins have releases (beta or otherwise) that work with webpack 4. Any help here would be 👌 

### Working Loaders / Plugins
- babel-loader (7.1.3)
- css-loader (0.28.10)
- less-loader (4.0.6)
- resolve-url-loader (2.3.0)
- sass-loader (6.0.7)
- sass-resources-loader (1.3.3)
- stylus-loader (3.0.2)
- ts-loader (4.0.0)
- friendly-errors-webpack-plugin (1.7.0)
- webpack-chunk-hash (0.6.0)

### Likely Working Loaders / Plugins
These have not been updated but appear to work
- coffee-loader

### Unknown
- html-loader
- img-loader
- postcss-loader

### CODE REVIEW

**Comment by thecrypticace** [comment]
Heh, the tests pass locally but not on Travis because of chunk hash differences. Weird. I'll look into this soon-ish.

**Comment by tpraxl** [comment]
We should definitely talk about these hash-comparisons. They will always make tests fail when libraries change. I'm not sure if this should be desirable.

**Comment by tpraxl** [comment]
Hm.. the tests pass locally? I think that AppVeyor and travis fetch other library versions than your local system then. Might have to do with node version, yarn version, etc. Notice that yarn is being used for travis and appveyor, not npm.

**Comment by thecrypticace** [comment]
Yeah the tests pass locally. I'm not sure what's up with that. The only difference is the hash. And only for some of the files. Which is even stranger.

For example, in the kitchen sink test:
1. The manifest and vendor files are the same
2. So is `file.js`
3. app, all, and another are all different.

¯\_(ツ)_/¯

**Comment by tpraxl** [comment]
I currently don't have the time to investigate this. Otherwise I would have proposed to test this locally on on my system as well to see if we can narrow down the cause. Maybe I can do so in the next days.

**Comment by thecrypticace** [comment]
That's cool. I don't expect to get this PR done today. :P

I'm gonna spin up a few docker containers with diff versions of node later today to see if I can make things break.

**Comment by thecrypticace** [comment]
Ran tests in a docker container. Hashes different still. And they appear to be the same across node versions but different across operating systems.

I'm betting the `WebpackChunkHashPlugin` isn't working right.

**Comment by MohannadNaj** [comment]
Away from my PC right now, just want to point out that I got it vice versa, the kitchen sink test didn’t pass locally on my windows 10 64x PC, yesterday on the master branch, using yarn. Yet it was all passing on AppVeyor.

The kitchen sink (different hashes) and also another test related to the line endings expected ‘\n’ but was ‘\n\r’.

**Comment by thecrypticace** [comment]
lol, what the heck. I'm debating whether wildcarding the hashes in the assertion is a good idea or not. My thoughts are that it is ideal if all environments with the same modules resulted in the same chunk hashes. And have the tests verify this (like they _almost_ currently do)

cc @JeffreyWay What are your thoughts there? Perhaps we could also use Webpack build records to keep the chunk order in builds more stable (in case that could be causing problems).

**Comment by tpraxl** [comment]
Ok, just tried it locally. I'm running Linux Mint 18.3, node version 8.9.4, yarn version 1.3.2. Maybe this helps narrowing down the issue.

```
2 tests failed [17:02:10]



  features › mix › it compiles JavaScript and Sass with versioning
  /Projects/laravel-mix/laravel-mix/test/features/mix.js:71

   70:     compile(t, () => {                                         
   71:         t.deepEqual({                                          
   72:             "/js/app.js": "/js/app.js?id=435ac1eab0bedf4ddb35",

  Difference:

      Object {
        "/css/app.css": "/css/app.css?id=2d4a1c0cca02e0a221b2",
    -   "/js/app.js": "/js/app.js?id=435ac1eab0bedf4ddb35",
    +   "/js/app.js": "/js/app.js?id=345dc3845f5906cc198a",
      }

  compile (test/features/mix.js:71:11)
  hooks.done.callAsync.err (node_modules/webpack/lib/Compiler.js:185:14)
  AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:42:1)
  AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules/tapable/lib/Hook.js:35:21)
  emitRecords.err (node_modules/webpack/lib/Compiler.js:183:22)
  Compiler.emitRecords (node_modules/webpack/lib/Compiler.js:295:39)
  emitAssets.err (node_modules/webpack/lib/Compiler.js:177:10)
  hooks.afterEmit.callAsync.err (node_modules/webpack/lib/Compiler.js:281:14)
  AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
  AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules/tapable/lib/Hook.js:35:21)
  asyncLib.forEach.err (node_modules/webpack/lib/Compiler.js:278:27)
  done (node_modules/neo-async/async.js:2809:11)



  features › mix › the kitchen sink
  /Projects/laravel-mix/laravel-mix/test/features/mix.js:182

   181:                                                            
   182:         t.deepEqual({                                      
   183:             "/file.js": "/file.js?id=6535b4d330f12366c3f7",

  Difference:

      Object {
        "/file.js": "/file.js?id=6535b4d330f12366c3f7",
    -   "/js/all.js": "/js/all.js?id=221653d915a0ffed3e59",
    -   "/js/another.js": "/js/another.js?id=eb61a202e96dd4c32fb2",
    -   "/js/app.js": "/js/app.js?id=2f69d82fea8ba1c94669",
    +   "/js/all.js": "/js/all.js?id=2f1359d025e3ca9ba465",
    +   "/js/another.js": "/js/another.js?id=4607f66a16a1c90b79c4",
    +   "/js/app.js": "/js/app.js?id=582e7ce30476f3dbda85",
        "/js/manifest.js": "/js/manifest.js?id=c77b6df8ed8341a67bef",
        "/js/vendor.js": "/js/vendor.js?id=58e7fac7916b30d91382",
    -   "/somewhere/app.js": "/somewhere/app.js?id=2f69d82fea8ba1c94669",
    +   "/somewhere/app.js": "/somewhere/app.js?id=582e7ce30476f3dbda85",
      }

```

**Comment by thecrypticace** [comment]
Yeah, pretty much what I see in my docker container. I'm going to run it and capture the files with git to see what the compiled differences are.

I suspect it might actually have something to do with path names.

**Comment by thecrypticace** [comment]
Yep, it's due to path differences. (at least partially)

**Comment by thecrypticace** [comment]
When I run the versioning test in production mode `.options({production: true})` it appears that the output no longer includes path names and is therefore reproducible (at least on macOS and the Node  Docker container running linux)

**Comment by JeffreyWay** [comment]
Thanks, Jordan! I'll be working through this and a couple other PRs this week. If we can, we'll get a release out this coming week.

**Comment by thecrypticace** [comment]
Sounds great!

**Comment by thecrypticace** [comment]
Code splitting doesn't seem to be working correctly on Windows according to Appveyor. I'm not sure why this is. Any chance someone can provide some insight here? I'm gonna try to set up a Windows VM with node, npm, git, etc…  so I can test this but I'm not sure how long that'll take.

**Comment by thecrypticace** [comment]
Got Windows tests working again. It was a rather simple fix. I've also updated two loaders alongside the documentation of loader status at the top of the PR.

**Comment by thecrypticace** [comment]
It seems you didn't comment on a block of code (or GitHub is just being odd). The relevant code starts here:
https://github.com/thecrypticace/laravel-mix/blob/3c1f70c22465a1aeef0d87d4cdf46542eda889a1/src/components/Extract.js#L29-L37

Yes, it does generate the same files like in Webpack 3. And if you are using extract multiple times with custom file names those are also generated like in Webpack 3.

**Comment by ruchern** [comment]
Yes, I do not know how to comment the whole block. Anyway, thank you for confirming that the code will generate the same files as per Webpack 3.

**Comment by thecrypticace** [comment]
Just found an issue the tests aren't catching. I'll be working through it tomorrow. Extract seems to sometimes generate an extra chunk called `0.js`. I know how to fix this but I want to get the tests to properly fail first.

:/

**Comment by thecrypticace** [comment]
Alright, got that worked out.

@JeffreyWay As part of the fix I updated the manifest file to include all generated assets not just ones with explicit chunk names.

I can back out that change if need be we'll just need a better way of getting the tests to verify which files Webpack actually generated.

**Comment by thecrypticace** [comment]
Heh asset paths are full paths. Whoops.

**Comment by thecrypticace** [comment]
Seems like yarn is having problems right now on CI servers. All windows builds failed because of this and one linux build did.

**Comment by garygreen** [comment]
I would hold off on this for now. There are so many problems currently with the Extract Text Plugin with Webpack 4, some alarming ones such as this: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/745 - anyone using PostCSS, Sass, Less etc will find problems with the order of their css, it's been reported for a good few weeks now.

I have a feeling the developers are holding out because of the new Mini Extract Text Plugin which has been released, which has better support for Webpack 4 and easier to use https://github.com/webpack-contrib/mini-css-extract-plugin

I haven't tried it myself, pretty much gave up with trying to convert to Webpack 4, too many issues to deal with. I'm sure they'll all be worked out though.

**Comment by thecrypticace** [comment]
Oh, dear. That's good to know about, thanks for pointing that out! I rarely use the Extract Text Plugin so I didn't tested it as much as some other stuff.

Need to look @ the issues tab more often.

**Comment by garygreen** [comment]
Pssst - support for Webpack 4 in ETWP has officially been dropped, use the Mini Extract Text Plugin  instead. 😄

**Comment by thecrypticace** [comment]
Thanks for the update!

To anyone else peeking in, this is the mentioned package: https://github.com/webpack-contrib/mini-css-extract-plugin

I'll be taking a look at this soon. (Next day or two)

**Comment by ruchern** [comment]
@garygreen where do you see they drop support for `extract-text-webpack-plugin`?

**Comment by spaceemotion** [comment]
@ruchern https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/745#issuecomment-374548449

**Comment by lukepolo** [comment]
friendly-errors-webpack-plugin PR to watch : https://github.com/geowarin/friendly-errors-webpack-plugin/pull/63

**Comment by lukepolo** [comment]
webpack-chunk-hash PR to watch : https://github.com/alexindigo/webpack-chunk-hash/pull/18

**Comment by thecrypticace** [comment]
An update, I started working on replacing `extract-text-webpack-plugin` but am running into odd issues with the new CSS plugin even in vanilla Webpack installs. I'll post an update when I have more info or make any more progress on it.

**Comment by Smile42RU** [comment]
Hi @thecrypticace. How i can speed-up solve issue related with `extract-text-webpack-plugin`? May i donate you for your time?

**Comment by artemsky** [comment]
drop `extract-text-webpack-plugin` in favor https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by lukepolo** [comment]
Update :  https://github.com/alexindigo/webpack-chunk-hash is ready for webpack 4 now `(0.6.0)`

**Comment by thecrypticace** [comment]
Providing a quick update here:
1. I did eventually get the new plugin working in some scenarios in a vanilla install (and w/ Vue Loader v15)
2. The new plugin seems to always create a javascript file to go alongside the CSS file (which usually only has JSONP boilerplate in it).
3. Have not had much time to put to this. Hopefully going to get to it again this week.

**Comment by lukepolo** [comment]
Update : friendly-errors-webpack-plugin@1.7.0 for Webpack 4

**Comment by Smile42RU** [comment]
@thecrypticace Hey. Any updates with `extract-text-webpack-plugin`?

**Comment by thecrypticace** [comment]
@lukepolo and I are working on this here: https://github.com/thecrypticace/laravel-mix/pull/1

**Comment by lukepolo** [comment]
Good news! I've managed to get the tests pass except for 1, but we have an issue with having multiple instances of the `mini-css-extract-plugin`.

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/45

This upgrades to vue-loader to  15, which is in RC-2 as well. 

You can look at the changes here till we update this branch : https://github.com/thecrypticace/laravel-mix/pull/1

**Comment by JeffreyWay** [comment]
Thanks, guys. It's amazing how much work has been required for this webpack v4 upgrade. I really appreciate all the effort you've put into this.

If all tests but one are passing, we're getting pretty close. When you're ready for me to pull this in and put it through its paces, let me know.

**Comment by lukepolo** [comment]
@JeffreyWay are you against running prettier?

**Comment by garygreen** [comment]
> Thanks, guys. It's amazing how much work has been required for this webpack v4 upgrade

I second this, it's been a royal pain in the bum to upgrade to v4 with lack of documentation and poorly updated plugins.

Personally, I've skipped Webpack 4 and now looking forward to Webpack 5. I see 4 as more of an experimental release as core stuff is gonna change yet AGAIN for Webpack 5 as css and other stuff becomes more a first class citizen; no more css/url/extract loaders? W5 will probably be what W4 should have been. 😄

**Comment by JeffreyWay** [comment]
@lukepolo Yes, everything can run through prettier.

**Comment by stephan-v** [comment]
I love how Webpack is getting 400k+ a year in funding and can not manage to even get their documentation in check. No wonder this upgrade is such a hassle.

**Comment by lukepolo** [comment]
Nah, its just trying to generalize a complicated thing its harder than just writing plain webpack. We could just give people a webpack config and rip stuff out. but who wants that 😆

**Comment by thecrypticace** [comment]
PR Updated. Thank you again @lukepolo!

Next step is to investigate what'll be required to get the issue worked out with the mini-css-text-plugin.

**Comment by lukepolo** [comment]
For those who are interested : https://github.com/webpack-contrib/mini-css-extract-plugin/issues/45 is the issue we need to solve to finish this up.

**Comment by ruchern** [comment]
@lukepolo it appears that there is no implementation for multiple instances of MiniCssExtractPlugin based on Sokra’s reply.

**Comment by lukepolo** [comment]
Yes, thats why we are waiting for the issue to be solved.

**Comment by ruchern** [comment]
Oh. I was under the impression that you guys are asking for some help to fix that

**Comment by lukepolo** [comment]
sorry about that! word are hard for me 😆

**Comment by ruchern** [comment]
All good. I am the one who probably did not understand your reply correctly. 😂

**Comment by lukepolo** [comment]
@artemsky Thanks, updated the dep. from RC-2 to `15.0.1` woo! 

If anyone wants to help , we need the extract mini plugin enhanced to support multiple extractions 

webpack-contrib/mini-css-extract-plugin#45

**Comment by Dwood15** [comment]
Any status updates for this PR?

**Comment by lukepolo** [comment]
till webpack-contrib/mini-css-extract-plugin#85 gets fixed were stuck , feel free to follow that issue to keep up to date~

**Comment by edwinharly** [comment]
Will it be a problem if I upgrade the webpack version on `node_modules/laravel-mix/package.json` to webpack 4 by myself ? Because, I need to use typescript, and it won't compile because you're not using webpack 4

**Comment by thecrypticace** [comment]
Yes as there are numerous breaking changes in webpack 4.

**Comment by ev1stensberg** [comment]
Here if you need any help with webpack side of things @thecrypticace . Got assigned time at work to help you out with this PR

**Comment by lukepolo** [comment]
It sounds like the issue that is stopping this from being merged won’t be fixed till 5.0 , the issue now has a 5.0 milestone in the webpack repository.

**Comment by stephan-v** [comment]
Better wait for Webpack 7.0. By that time the documentation will probably have catched up to 4.0

**Comment by lukepolo** [comment]
@stephan-v 
Its not a documentation issue. 

There docs are great! It is also open source so feel free to make it better by making a PR.

**Comment by garygreen** [comment]
@lukepolo I think the reason why there's been against towards Webpack 4 is how poorly it's been pushed out there with little documentation, not much in terms of care form the maintainers (just look at issues on github) and there's been quite a lot of shedding of stuff "we'll just fix it in webpack 5".

I'm sure you can't deny given that this PR has been in the making since Feb how challenging it is... should it be this challenging? I'm not convinced it should be, IMO.

Your correct it is open source, but the core contributors do get paid and Webpack receive a fair amount of donations from sponsors, so meh. There's reason to be a bit salty, I guess 😄

**Comment by Dwood15** [comment]
@ev1stensberg They definitely need help on that css loader.

**Comment by artemsky** [comment]
Look like we all waiting for wp5 release.

**Comment by Dwood15** [comment]
There seems to be some movement on this issue.

https://github.com/fqborges/webpack-fix-style-only-entries

**Comment by montogeek** [comment]
@stephan-v Why you don't try to contribute to webpack 4 docs? There is 400k available for you, What is stopping you?

**Comment by montogeek** [comment]
@thecrypticace "Currently blocked by an issue in mini-css-extract-plugin" it the only blocker at this moment?

**Comment by thecrypticace** [comment]
Yeah that was the only big main blocker. I need to rebase this branch but I have a feeling WP5 will be released before that issue gets completely and properly fixed.

I need to do some more testing and research around this I just don't have the time currently. Maybe w/in the next few weeks I can pick this up again hopefully.

**Comment by montogeek** [comment]
@lukepolo That isn't possible. What is the use case?
Could you please point me how it works on v3?
It is this one?
```js
mix.js(src, output)
   .extract(['any', 'vendor', 'library']);
```
?

I would like to see webpack 4 on laravel-mix, we are leaving 62k users weekly without the advantages of webpack 4.

**Comment by thecrypticace** [comment]
What do you mean that's not possible? When using the CSS extract plugin + chunk splitting extra JS files that _must_ be loaded get generated named after the CSS chunks. It's a odd problem but a definite one nonetheless.

**Comment by montogeek** [comment]
What is the issue? Remove those JS chunks?

**Comment by thecrypticace** [comment]
You can't just delete them. They're present in the webpack manifest so if you do your app won't load. But yeah you have to get webpack to not generate them.

**Comment by azdanov** [comment]
Would it be possible to create a `@next` branch with experimental webpack 4 support or is the issue with `mini-css-extract-plugin` completely breaks mix builds?

**Comment by willypuzzle** [comment]
There is any hope that this PR will be committed nearly?

**Comment by tiagosv** [comment]
Hi, where's this at?

**Comment by Saibamen** [comment]
Could you update css-loader to get rid of deprecated cssnano?

**Comment by stephan-v** [comment]
Still waiting on this PR like

image

**Comment by Dwood15** [comment]
Needs some work on the Mini Css Webpack Extract plugin so it doesn't create an extra javascript file for lone css entries.

There's been a few people who've said they'd work on it, but they tend to disappear.

**Comment by thecrypticace** [comment]
It's very possible that this will have to wait for Webpack 5. I _believe_ the issue has already been resolved there but I need to verify to be sure.

**Comment by Dwood15** [comment]
Looks like there's a PR for adding CSS support to webpack. 

See the Webpack 5 milestone here: https://github.com/webpack/webpack/milestone/18

**Comment by CurtisConway** [comment]
@thecrypticace - Are you 100% just waiting on Webpack 5?

There's some webpack plugins that require version 4 to operate, and thus are completely unusable if you're using mix. (CKEditor 5 is one example: https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/ckeditor5-dev-webpack-plugin).

This doesn't affect me in any immediate fashion, but it would be nice to know when version 4 is officially supported.

**Comment by lukepolo** [comment]
Unless (https://github.com/webpack/webpack/pull/8124) gets merged into webpack 4, cant really do much until 5 gets released.

**Comment by CurtisConway** [comment]
> Unless ([webpack/webpack#8124](https://github.com/webpack/webpack/pull/8124)) gets merged into webpack 4, cant really do much until 5 gets released.

Thank you for the confirmation.

**Comment by garygreen** [comment]
Maybe a bit off topic - but has anyone tried Parcel or can recommend any other bundlers? I'm becoming increasingly frustrated with Webpack and it's maintainers. The codebase behind it is so complex I suspect that's part of the reason why it's so difficult fixing things. I had a look at Parcel and it seems far easier to understand and development seems active. Any thoughts? 😃

**Comment by thecrypticace** [comment]
Yep. I've used it on a project. From what I can tell, unless you're using async imports, It does not have a way to do common chunk splitting (i.e. split vendor code into a separate bundle).

**Comment by spaceemotion** [comment]
@thecrypticace have you used it in a laravel environment? if that's the case, how did you manage to extract the manifest.json?

**Comment by thecrypticace** [comment]
I did. It does not appear to do versioning either (maybe?) so I didn't use the `mix()` calls. I'm looking into writing a plugin for it if/when I possibly get time to unless someone gets to it before me.

**Comment by azdanov** [comment]
There is versioning: https://parceljs.org/production.html#file-naming-strategy.

Although no easy way to get a manifest file. So a custom solution could be made based on its api: https://parceljs.org/api.html.

**Comment by garygreen** [comment]
What about [FuseBox](https://fuse-box.org)? It seems the most Laravel-y of all the JS bundlers

**Comment by sebastiandedeyne** [comment]
In case anyone's interested, in some projects we started to replace Mix with a custom and relatively light weight Webpack 4 configuration for Vue and Tailwind.

https://github.com/spatie/webpack

**Comment by JeffreyWay** [comment]
Hey, everyone. I've been working on the webpack v4 upgrade all day. 

So I have some sense of what all this code does, I've been doing the upgrade from scratch, slowly pulling from this PR, as I follow webpack's upgrade steps. Otherwise, it's just too confusing to know why things were added/removed. Thanks to Jordan and Luke in particular for all their work. It has been massively helpful as I work through this.

I currently have all tests passing except one. This one:

```
features › vue › it extracts vue styles to a dedicated file

  /Users/jeffreyway/code/laravel-mix/test/features/vue.js:92
```

My hope is to tag a beta release by the end of the week, if we can get this sorted.

**Comment by thecrypticace** [comment]
> it extracts vue styles to a dedicated file

This was basically the one thing that I was working on. If you want this to work as it did in webpack 3 you're going to have to wait for webpack 5.

**Comment by thecrypticace** [comment]
The main issue is that chunk splitting CSS files _also_ generates almost empty JS files that you must include or your app won't load.

**Comment by JeffreyWay** [comment]
Ugh this is so frustrating. How are other tools like webpacker/encore/etc handling this? I hate that this is the only thing keeping us from getting this out the door. And I can't seem to find any general release date for webpack 5. So who knows when this will be fixed.

**Comment by thecrypticace** [comment]
Honestly, I'm not sure that they are. It's possible to get it to place Vue CSS in the main CSS file but as soon as you try splitting CSS at all you run into issues.

**Comment by lukepolo** [comment]
If they use that feature Id just put a warning they need to include all files emitted. Annoying, but it will make their build work.

There are also some improvements you can make , specifically 

- [Named Chunks](https://github.com/variejs/varie-bundler/blob/master/plugins/NamedChunks.js) (vue cli had a some issues without as adding a file and the cache loader not working properly) 
- [cache-loader](https://github.com/variejs/varie-bundler/blob/master/loaders/Loader.js#L16) / [thread-loader](https://github.com/variejs/varie-bundler/blob/master/loaders/Javascript.js#L17) for rebuilding performance


You can view the whole source here : 
https://github.com/variejs/varie-bundler

**Comment by garygreen** [comment]
image
...for Webpack 5

**Comment by JeffreyWay** [comment]
haha. Well I'm hoping to not wait for webpack 5. Spending the day on this.

**Comment by paulcsmith** [comment]
You’ve probably thought of this already, but if you can’t get it working an alternative might be to release a new major version of Mix that only supports webpack 4 with the caveat that it will have issues with that particular use case. That way people that don’t need the file splitting can use the newest versions and people that do can use the previous version of Mix until webpack 5 comes out.

**Comment by JeffreyWay** [comment]
@paulcsmith Yep that's almost exactly what we'll end up doing.

**Comment by JeffreyWay** [comment]
@thecrypticace @lukepolo Sorry for being behind the curve here. Just want to make sure I fully understand the problem. Is this what you're referring to?

example

So if I try to split CSS files, it'll create an unnecessary JS file of the same chunk name. That's the issue?

One thing I'm noticing, in the example above, is that if I just ignore `thing.js` entirely, the app loads correctly. ...Unless I'm missing something.

**Comment by lukepolo** [comment]
It's the css extraction from `vue` that causes the issue. As it creates empty JS chunks when removing the CSS.

**Comment by JeffreyWay** [comment]
Okay, let's just do that and be done with it.

**Pull request closed without merging**
