### PR TITLE
WIP: Add failing test for issue #1118

### PR DESCRIPTION
**Pull request by rtheunissen**
See #1118, which was closed but not resolved.

### CODE REVIEW

**Comment by rtheunissen** [comment]
I think this should somehow consider the `output` path, if provided: https://github.com/JeffreyWay/laravel-mix/blob/master/src/components/Extract.js#L74

**Comment by rtheunissen** [comment]
This gets tricky with multiple extractions, because they may not share the same base path.

**Comment by rtheunissen** [comment]
Overriding `optimization.runtimeChunk.name` has no effect, so not sure where that path is generated in the first place. Seems like there are multiple unresolved issues about this:
- https://github.com/JeffreyWay/laravel-mix/issues/1118
- https://github.com/JeffreyWay/laravel-mix/issues/1203
- https://github.com/JeffreyWay/laravel-mix/issues/1695

**Comment by rtheunissen** [comment]
We ended up adjusting our public path to accommodate this.

**Comment by culturegr** [comment]
@rtheunissen could you please elaborate on this 
> We ended up adjusting our public path to accommodate this?

It seems that the problem still exists (see #1118), meaning that `manifest.js` is not created in the same directory as `vendor.js`

**Pull request closed without merging**
