### PR TITLE
Update packages to fix security vulnerabilites

### PR DESCRIPTION
**Pull request by ruchern**
screen shot 2018-01-21 at 12 58 44 pm

The screenshot of the problem.

### CODE REVIEW

**Comment by tpraxl** [comment]
This merge broke the tests. See [Travis CI](https://travis-ci.org/tpraxl/laravel-mix/jobs/331456438) and [AppVeyor](https://ci.appveyor.com/project/tpraxl/laravel-mix/build/1.0.33). This issue is also a good reason for merging #1425 IMHO.

**Comment by tpraxl** [comment]
Also, why has the yarn.lock been removed?

**Comment by ruchern** [comment]
On breaking the tests, I did not change anything on the test. I checked the test before and after and it's the exact same results. I think the test is already broken before I did anything. I would love to fix it, but I am very new to testing for now.

On the topic of `yarn.lock` being removed, I was the one who merged the `yarn.lock` by accident into the repo because I am using yarn. I do think we will need that and lets keep it simple to one "package lock" file.

**Comment by tpraxl** [comment]
@ruchern my comment was no offense, really. The tests include comparison of file hashes and the file hash changed because of the library updates. This is normal. You didn't break laravel-mix, only the tests failed. I fixed that in #1425 to make sure that the automatic tests work immediately, should @JeffreyWay merge my PR. It's just a minor matter.

I also restored the yarn.lock in that PR, because it's important for deterministic test data currently (especially in node 6 environment on windows for AppVeyor).

**Comment by ruchern** [comment]
Right, it makes sense that the file hash changes when the libraries are updated. Should that be more dynamic in this case since updating packages will change the hashes regularly and subsequently failing the test.

**Comment by tpraxl** [comment]
Yes, I know that this test will fail over and over again after library updates. And I'm not sure what the intention for this test was originally (maybe I should watch the respective episode on laracasts again :) ). Just wanted to add automatic testing for all supported platforms and versions with reduced impact on the rest of the code.

I believe that – once automated tests are integrated – there will be discussions about tests that may not be 100% optimal and finally the situation will improve (I will gladly contribute to that). However, I didn't address this very test in this PR, because that's another story that should be discussed elsewhere to avoid blurring the focus of this PR.

**Pull request merged**
