### PR TITLE
Stylus support

### PR DESCRIPTION
**Pull request by rogervila**
Adds stylus support

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Going to close this for now. This is how tools like this get horribly bloated. 

It's best to manually add the loader to your webpack.config.js.

Thanks!

**Comment by rogervila** [comment]
No problem Jeffrey.

[I have made a fork](https://github.com/rogervila/laravel-mix-stylus), so I can install Mix with stylus support in only one command.

**Comment by terion-name** [comment]
@rogervila you have issues disabled :(
mix manifest is not written with your verison

```
mix
    .js('resources/assets/js/app.js', 'public/assets/js')
    .js('resources/assets/js/ui.js', 'public/assets/js')
    .stylus('resources/assets/stylus/app.styl', 'public/assets/css')
    .extract(['vue'])
    .sourceMaps()
	.version();
```

and webpack.config is that you provide, just added some options to stylus loader

**Comment by rogervila** [comment]
Hi @terion-name, sorry I did not realize that issues were closed.

Now I'm cloning the 0.5.x version of Mix and adding default stylus support.

Thank you!

**Pull request closed without merging**
